### ISSUE TITLE
i bet you anything

### ISSUE THREAD

**Issue by jbxskm** [interstellarnetwork/interstellar#10]
my school will block this in less then a week.

**Comment by imbubbo** [comment]
@jbxskm join our discord then!

**Comment by imbubbo** [comment]
https://discord.gg/gointerstellar

**Comment by jbxskm** [comment]
i dont have discord

**Comment by imbubbo** [comment]
use a proxy or ur phone??

**Comment by jbxskm** [comment]
i dont have a phone and pr*xys make me verify a phone number
no thanks
