### ISSUE TITLE
New Game Reccommendation! 

### ISSUE THREAD

**Issue by TrickJoker312** [interstellarnetwork/interstellar#11]
I would very much appreciate it if you could add the Lofi Funkin mod from Friday Night Funkin. Could you please add this? I'd seriously really appreciate it!

**Comment by imbubbo** [comment]
Can you send me a link of it?

**Comment by imbubbo** [comment]
@TrickJoker312

**Comment by TrickJoker312** [comment]
Oh, i can!

**Comment by TrickJoker312** [comment]
Here ya go! https://kbhgames.com/game/friday-night-funkin-lofi-funkin

**Comment by imbubbo** [comment]
@TrickJoker312 its added!

**Comment by imbubbo** [comment]
This game has been added.

**Comment by TrickJoker312** [comment]
Thank you so much! I really appreciate it!
