### ISSUE TITLE
Bubbo help?

### ISSUE THREAD

**Issue by LiamSirBean** [interstellarnetwork/interstellar#112]
What is this page: https://gointerstellar.app/ deployed with?

**Comment by imbubbo** [comment]
We use a VPS.

**Comment by LiamSirBean** [comment]
Which one?

**Comment by imbubbo** [comment]
It's self hosted

**Comment by LiamSirBean** [comment]
A VPS is a website that helps you host your website. So how is it self hosted if you use a VPS?

**Comment by imbubbo** [comment]
A vps isn't a website..
