### ISSUE TITLE
Discord blocked, just list the links in a .txt or something

### ISSUE THREAD

**Issue by PSYclownYT** [interstellarnetwork/interstellar#117]
Our school uses lightspeed systems along with a firewall responsive, where it blocks with the proxy even if the extension is terminated.
I have tried using LTbeef, 3kh0/ext-remover, and discord is blocked.

lightspeed systems ext. id:
adkcpkpghahmbopkjchobieckeoaoeem

thank you for your time.

**Comment by LiamSirBean** [comment]
Make a bookmarklet with this code: javascript:open('/document/d').onload=function(){this.chrome.runtime.sendMessage('gndmhdcefbhlchkhipcnnbkcmicncehk',{command:'lock'},close)} Now open google docs and make a new document. Now click the bookmarklet you just made. It should do a bunch of goofy stuff but all of your extensions including lightspeed should be gone. It works on almost every version so good luck!

**Comment by 12944qwerty** [comment]
Also a lightspeed school here, bookmarklets are blocked here. How would I do this otherwise?

**Comment by LiamSirBean** [comment]
So I made a proxy that should redirect to interstellar so here are the steps. 1. go to https://max-ez.pages.dev/ but don't press continue. 2. Click on the lock icon left of the address bar. 3. Make sure pop-ups and redirects are allowed. 4. Refresh the page. You should now see an about:blank page and this means you are cloaked. You may now press continue.

**Comment by LiamSirBean** [comment]
If pop-ups and redirects are managed by you admin (forced off) you better pray that google sites is unblocked because this site is your last option until a new interstellar unblocked link comes out. The site is https://sites.google.com/view/learn-sci/rammer_1

**Comment by PSYclownYT** [comment]
no theres no way to get past the firewall. i already have many different ways to get on 1-layer blocked sites, just not discord, as its also blocked by firewall.

**Comment by PSYclownYT** [comment]
> Also a lightspeed school here, bookmarklets are blocked here. How would I do this otherwise?

3kh0/ext-remover
