### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LiamSirBean** [interstellarnetwork/interstellar#127]
How do you get apps like google to work because when I try a code that opens them in about:blank it says unable to find but with your proxy it does work. PLEASE HELP BUBBO!

**Comment by LiamSirBean** [comment]
Im guessing it has something to do with the bare server node script but idk.

**Comment by PSYclownYT** [comment]
try using the following bookmarklet to cloak tabs:
javascript:var%20%24jscomp%3D%24jscomp%7C%7C%7B%7D%3B%24jscomp.scope%3D%7B%7D%3B%24jscomp.createTemplateTagFirstArg%3Dfunction(a)%7Breturn%20a.raw%3Da%7D%3B%24jscomp.createTemplateTagFirstArgWithRaw%3Dfunction(a%2Cb)%7Ba.raw%3Db%3Breturn%20a%7D%3Bvar%20frame%3Ddocument.createElement(%22iframe%22)%3Bframe.src%3Dprompt(%22What%20URL%20do%20you%20want%20to%20visit%3F%20(please%20start%20with%20https%3A%2F%2F%20or%20it%20will%20fail!!!1!)%22)%3Bvar%20stl%3Dframe.style%3Bstl.position%3D%22fixed%22%3Bstl.left%3Dstl.right%3Dstl.top%3Dstl.bottom%3Dstl.margin%3Dstl.border%3D%220%22%3Bstl.border%3D%22none%22%3Bstl.width%3Dstl.height%3D%22100%25%22%3Bstl.setProperty(%22z-index%22%2C%229999%22)%3Bstl.setProperty(%22background-color%22%2C%22%23FFFFFF%22)%3Bdocument.body.appendChild(frame)%3Bvar%20btn%3Ddocument.createElement(%22button%22)%3Bbtn.addEventListener(%22click%22%2Cfunction()%7Bframe.style.display%3D%22none%22%3D%3Dframe.style.display%3F%22block%22%3A%22none%22%7D)%3Bbtn.style%3D%22position%3A%20fixed%3B%20%5Cnbottom%3A%200%3B%20%5Cnright%3A%200%3B%20%5Cnmargin%3A%2020px%3B%20%5Cnz-index%3A%2099999%3B%5Cnborder%3A%20none%3B%5Cnfont-size%3A%2014px%3B%5Cnpadding%3A%203px%3B%5Cn%22%3Bbtn.innerHTML%3D%22Toggle%22%3Bdocument.body.appendChild(btn)%3Bvoid+0

**Comment by LiamSirBean** [comment]
Thanks
