### ISSUE TITLE
logo idea

### ISSUE THREAD

**Issue by PSYclownYT** [interstellarnetwork/interstellar#136]
![interstellar (1)](https://user-images.githubusercontent.com/116015847/230956059-9dd16db8-5292-48da-97be-012ee67c8999.png)
I hope it looks cool after compression

**Comment by LiamSirBean** [comment]
Cool! It's a little dark, so it might be hard to see tho.

**Comment by imbubbo** [comment]
if u can make it a bit brighter ill use it!

**Comment by imbubbo** [comment]
oops i closed

**Comment by LiamSirBean** [comment]
I love it! The brightness is perfect, and I think it will fit perfectly with the interstellar theme.
