### ISSUE TITLE
Can’t deploy on glitch anymore 

### ISSUE THREAD

**Issue by ranvirsi1** [interstellarnetwork/interstellar#147]
It seems like glitch doesn’t allow proxies as I deployed a interstellar link and after 5 sec it got suspended I don’t know what happened 
![B5CCA1E8-02F2-458A-9EA5-ABE80C8EDF37](https://user-images.githubusercontent.com/100595269/235010464-c1a8a2da-ca9c-48ca-993f-9682c86c4774.png)

**Comment by imbubbo** [comment]
Glitch doesn't like proxies
