### ISSUE TITLE
Heroku deployment not working

### ISSUE THREAD

**Issue by opal98** [interstellarnetwork/interstellar#156]
Hello, I have tried to deploy interstellar on to my heroku account, which I pay for, but it is not working. None of the games or apps are loading and the proxy isn't working. What should I do?

**Comment by CroftOG** [comment]
cry

**Comment by Bigfoot9999** [comment]
> Hello, I have tried to deploy interstellar on to my heroku account, which I pay for, but it is not working. None of the games or apps are loading and the proxy isn't working. What should I do?

Please send a few screenshots of the error you are receiving.

**Comment by Shadow-Afton** [comment]
How can I open this proxy up?
