### ISSUE TITLE
Light theme hides text

### ISSUE THREAD

**Issue by Nebelung-Dev** [interstellarnetwork/interstellar#170]
Change the text color on the nav to fix.
![image](https://github.com/interstellarnetwork/interstellar/assets/81875430/191088f9-cd3f-49d3-8cb7-fe636697df63)
This: Interstellar Proxy Games Apps Chatroom Settings

**Comment by energeticnetwork** [comment]
Uh to be honest i can just add that on a pr so k

**Comment by Xoui** [comment]
im energetic on my chromebook

**Comment by xbubbo** [comment]
Light mode is a joke, it's intentional.
