### ISSUE TITLE
Can't create through Oracle Cloud

### ISSUE THREAD

**Issue by DiBiaseProductions** [InterstellarNetwork/Interstellar#178]
I click the link set the name accept terms and it gives me thie error Message, "The file is not a .zip file, or it doesn't contain any Terraform configuration files." 
<img width="1721" alt="Screenshot 2023-06-14 at 4 59 47 PM" src="https://github.com/interstellarnetwork/interstellar/assets/126369822/37984cbe-1704-41e1-9c73-98fa09f8addb">

**Comment by energeticnetwork** [comment]
what are you trying to create cuz the link is
https://github.com/interstellarnetwork/interstellar.git

**Comment by DiBiaseProductions** [comment]
I just click your button on the main page for oracle cloud

**Comment by MicroChipKali** [comment]
same it is now working for me
