### ISSUE TITLE
Can't deploy to cyclic.sh

### ISSUE THREAD

**Issue by energeticnetwork** [interstellarnetwork/interstellar#179]
![image](https://github.com/interstellarnetwork/interstellar/assets/134102421/9bc5c97c-0033-4a7a-bbe2-45a9163583d4)

**Comment by DiBiaseProductions** [comment]
just change the code where it says name to something else and see if it works as it is only highlighting the "name" section in red so it may be filtering based on popular use

**Comment by energeticnetwork** [comment]
@DiBiaseProductions  Nope. not it its because of the UV dependency the name has nothing to do with it i asked chat gpt the lowest word used. then put in name not the problem.

**Comment by Packjackisback** [comment]
yeah that or the code
