### ISSUE TITLE
i cant make website with onrender

### ISSUE THREAD

**Issue by PiErCeEsBoT12** [InterstellarNetwork/Interstellar#188]
i have done this before and it worked amazing but now when i fill in the info and click the button create web service it says there is an error above please fix it and there is nothing i can do to fix it. I jst wanted to know if other people are having this problem and how i could fix it.

**Comment by ranvirsi1** [comment]
im haveing the same thing here

**Comment by ranvirsi1** [comment]
its says repo invalid

**Comment by xbubbo** [comment]
join the discord for a workaround.
