### ISSUE TITLE
No Longer Supports Railway

### ISSUE THREAD

**Issue by TornadoRoad46** [InterstellarNetwork/Interstellar#189]
It has came to my attention that Railway has BANNED ultraviolet from their platform. Since InterstellarNetwork is sorta built on ultraviolet, it will not allow you to build this repo to Railway. Railway should probably be removed from the "Deploying" tab on the Github repo. 

![image](https://github.com/InterstellarNetwork/Interstellar/assets/78221040/59c60168-88c1-403a-9ea9-69b89b51c353)

**Comment by imbubbo** [comment]
Thank you.
