### ISSUE TITLE
How do you deploy to VSC

### ISSUE THREAD

**Issue by jeffruizx** [InterstellarNetwork/Interstellar#193]
Visual Studio Code

**Comment by imbubbo** [comment]
You mean like the website?

**Comment by Xoui** [comment]
U cant

**Comment by jeffruizx** [comment]
> You mean like the website?

yes

**Comment by jeffruizx** [comment]
> U cant

y

**Comment by impaxton** [comment]
you open a terminal and run the batch commands that youd normally run

**Comment by Xoui** [comment]
vscode.dev doesent work like use gitpod

**Comment by jeffruizx** [comment]
> vscode.dev doesent work like use gitpod

how? how would I deploy, i've never used gitpod
