### ISSUE TITLE
Willing to help build and contribute to interstellar

### ISSUE THREAD

**Issue by jacksoncraft859** [InterstellarNetwork/Interstellar#205]
Hey everyone at Interstellar, My name is Jackson. Recently my School has blocked all VPNs and Proxy's, So I've been deploying my own interstellar servers for me and my friends, and I have some ideas that can make Interstellar "the next level proxy". I can code fluently in Python, Node.JS, and Shell script. So Please email me at jacksoncraft859@gmail.com if you have any questions or consider allowing me to join. Thanks, 
Jackson and everyone at Ultrix.

**Comment by GhostXDev** [comment]
If you would like to help me with a project that would be greatly appreciated email me at [mnv2_dev@outlook.com](malito:mnv2_dev@outlook.com)

**Comment by juniorbutyeah** [comment]
open up a ticket on our discord https://discord.gg/interstellar
