### ISSUE TITLE
[Bug] Scratch games don't work

### ISSUE THREAD

**Issue by Zachary-Rude** [InterstellarNetwork/Interstellar#212]
I see that there are some Scratch games on this website. However, they always crash, with the error being `o.__uv$setSource is not a function` or something similar. I want to know why that happens, and for you to fix it. Until you fix it, I won't be able to add any Scratch games to this website.

**Comment by GhostXDev** [comment]
Please note that v5 just released and there will be some bugs. We will get on it as soon as possible.

**Comment by Zachary-Rude** [comment]
interstellar has actually had this issue in v4 as well, but never got fixed in v5

**Comment by Zachary-Rude** [comment]
also, please add the bug label to this issue because i can't add them myself

**Comment by GhostXDev** [comment]
Welp I can see whats wrong it might be the servers also cause people keep reporting that they are slow. I will bring it to Bubbo's attention.

**Comment by Zachary-Rude** [comment]
ok

**Comment by PSYclownYT** [comment]
temporary fix = scratch is unblocked for most schools and network firewalls, and there is a turbowarp packager standalone - go to their github to find it

**Comment by SHAD0wJJ1313** [comment]
How do i get on different versions?

**Comment by GhostXDev** [comment]
There are no other hosted versions of interstellar since the servers are only hosting the public version of the site which is v5. Now if you want to host a version of a site that is possible join our discord to figure out how to host a domain
