### ISSUE TITLE
I can't get onto the .hop. version of interstellar.

### ISSUE THREAD

**Issue by Bl00man** [InterstellarNetwork/Interstellar#213]
I would just like to know if this is just me or if I did something wrong, I cannot connect to the Instellar.hop.sh page and it keeps giving me a "Deployment Unavailable There are no containers available to serve this request. If you're the developer, you can create containers using our console or API." I'm just not sure what to do with this. what can I do here?

![image](https://github.com/InterstellarNetwork/Interstellar/assets/128631608/af01a0b6-5ff7-409e-8c04-870175bc768e)

**Comment by GhostXDev** [comment]
Are you hosting the site?

**Comment by Bl00man** [comment]
> Are you hosting the site?
No, I got the website from a friend.

**Comment by Bl00man** [comment]
> Are you hosting the site?

To be fair, I have no idea what I'm doing. :p If you guys can recommend anything let me know plz

**Comment by GhostXDev** [comment]
Try asking someone from the discord server.

**Comment by GhostXDev** [comment]
Also the site domain if he was hosting it might've gotten shot down

**Comment by Bl00man** [comment]
> Try asking someone from the discord server.

Thank you!

**Comment by GhostXDev** [comment]
No problem man just friendly dev here :D

**Comment by imbubbo** [comment]
The person who gave you link, shouldn't of shared it.

They also gave you the wrong link, so that's why it isn't working.
