### ISSUE TITLE
[Question] Why can't you deploy Interstellar on Netlify?

### ISSUE THREAD

**Issue by Zachary-Rude** [InterstellarNetwork/Interstellar#215]
I would deploy Interstellar on Netlify if i wanted to, but I can't. I can't deploy it on Replit because: 
1. Websites hosted on it are _**unfortunately**_ blocked at my school.
2. For _**some**_ reason, websites hosted on it automatically go down after a while, which I <ins>**don't**</ins> want.

Therefore, I would like to know <ins>why</ins> Interstellar can't be deployed on Netlify.

**Comment by imbubbo** [comment]
Interstellar is a dynamic site, with a backend.

Netlify doesn't support backends, and the proxy will not work on Netlify.
