### ISSUE TITLE
i cant deploy to render 

### ISSUE THREAD

**Issue by Treezyspecial** [InterstellarNetwork/Interstellar#222]
I really need help i want to deploy to render but it keep saying this action is not allowed but i see people make links somehow anyway can someone help?

**Comment by TornadoRoad46** [comment]
Having the same issue
![image](https://github.com/InterstellarNetwork/Interstellar/assets/78221040/bdcb43f8-ab8a-490e-ba65-634a2ecda7cb)

**Comment by xbubbo** [comment]
@Treezyspecial @TornadoRoad46 join our discord (https://discord.gg/interstellar) and go to the #tutorials channel and follow the steps in there.

**Comment by Treezyspecial** [comment]
i cant join the discord bc i cant make an account could u send a screenshot or copy the instructions and paste theM?
