### ISSUE TITLE
[bug] spotify doesn't work

### ISSUE THREAD

**Issue by FU3X** [InterstellarNetwork/Interstellar#234]
When I go to Spotify on the apps listed, it doesn't load and leave a blank screen. 

Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by RisingGlitch** [comment]
> When I go to Spotify on the apps listed, it doesn't load and leave a blank screen.
> 
> Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

Spotify doesn't work on UV, so their isn't much we can do.

**Comment by FU3X** [comment]
> > When I go to Spotify on the apps listed, it doesn't load and leave a blank screen.
> 
> > 
> 
> > Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
> 
> 
> 
> Spotify doesn't work on UV, so their isn't much we can do.

wdym "uv"?

**Comment by isayaacorn** [comment]
> wdym "uv"?
Ultraviolet, the proxy being used in Interstellar.
