### ISSUE TITLE
Blocked By Securly

### ISSUE THREAD

**Issue by HXCHS** [InterstellarNetwork/Interstellar#253]
WOrked awsome! But damn securly blocked it! I created my own website with clockwork os, see my repo pinned on my profile with 37 stars, but now interstellar is blocked, securely is gonna go after nebula next, please fix!!!!

**Comment by LiamSirBean** [comment]
Get a new link.

**Comment by airtag8892** [comment]
https://discord.gg/interstellar for more links

**Comment by xbubbo** [comment]
https://discord.gg/interstellar for more links
