### ISSUE TITLE
[Bug] Connection reset error

### ISSUE THREAD

**Issue by Zachary-Rude** [InterstellarNetwork/Interstellar#263]
Hello,
Most of the Interstellar links I've tried just say "The connection was reset" when accessing them on my school computer. Why is this, and would you please fix it?
I would like some links, but I'm **not** joining your Discord server, especially not after everyone on there started bullying me...

**Comment by xbubbo** [comment]
Fixed, Also not sure what bullying you're talking about since we don't allow bullying/harassment in our discord server.
