### ISSUE TITLE
[Bug] Captchas cannot load

### ISSUE THREAD

**Issue by Scottcamatic** [InterstellarNetwork/Interstellar#264]
Hello, 

I was attempting to use Discord via Interstellar, but the Captchas won't load. Here's the image proof: 
![canvas](https://github.com/InterstellarNetwork/Interstellar/assets/148129727/c3462de1-2645-428b-acca-5430663b7ffe)
I apologize if this was posted before, as I did not find anything searching the bug reports, nor can I access Discord to ask in the server.

Thank you in advance.

SOLUTION: I found the solution is to use the Discord Login shortcut from the Apps section of the website instead of googling the URL, which causes the problem. Sorry to waste time!

**Comment by jacksoncraft859** [comment]
Try and see if another proxy works if you want you can try mine: it’s called evasi. https://evasi.ultrix.online

**Comment by Scottcamatic** [comment]
> Try and see if another proxy works if you want you can try mine: it’s called evasi. https://evasi.ultrix.online

Blocked on my school wifi for being un-managed.

**Comment by jacksoncraft859** [comment]
try this link that link was on my new domain: https://evasi.netlify.app

**Comment by xbubbo** [comment]
@Scottcamatic

Use the Discord - Login app on the apps page.
