### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by odin29** [InterstellarNetwork/Interstellar#267]
I would've put this in Discord, but Discord is blocked for me.  When I attempt to deploy to render, it hits me with the error "educational-template (invalid repository)"

Here is screenshot
![image](https://github.com/InterstellarNetwork/Interstellar/assets/117384117/bf69ba41-b7af-49a4-80c4-6b6237531637)

How do i fix this?

**Comment by WaveDemure** [comment]
use my repo "push92"
https://github.com/WaveDemure/push92
