### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by kedoboxx** [InterstellarNetwork/Interstellar#270]
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

every time I use it, it gives me this error. I've tried on different networks and devices, deployments both online and local. 
Only consistency is that all the devices are Windows.

Screenshot:
![image](https://github.com/InterstellarNetwork/Interstellar/assets/104593983/e490c0fd-b1a6-47d3-b461-59c71c84d27c)
 
Ive tried Replit, Google Cloud, Glitch (Glitch never works), Render (Render doesn't load the repo), Cyclic (Cyclic just never loads either), and Oracle Cloud.
Help!

**Comment by xbubbo** [comment]
Show me the link that is giving this error.

**Comment by kedoboxx** [comment]
> Show me the link that is giving this error.

its just me cloning the repo on different sources. That one specifically was from Google Cloud

**Comment by kedoboxx** [comment]
For the Google Shell, I'm just copying the instructions that are listed in the current README for Replit. I get to the main Interstellar page but when I look anything up, search anything on tabs, or click on any pre-provided links/games, it just gives me the error from the first ss

This is generally what I get:
![image](https://github.com/InterstellarNetwork/Interstellar/assets/104593983/dda10769-c33c-4019-b390-fb48d75cfd7c)
I run the commands in Google Cloud and go to that localhost

![image](https://github.com/InterstellarNetwork/Interstellar/assets/104593983/bd8db122-ee3f-4c73-9ae3-fb170ab48dbc)
It gives me this, which is the normal Interstellar page

![image](https://github.com/InterstellarNetwork/Interstellar/assets/104593983/8196f7fa-0169-4b9d-a3bb-1d8d28818326)
Then regardless of what I type in the bar or do after, I get the status error. 

not sure if that explains it a bit more or helps in any way.

**Comment by xbubbo** [comment]
Whenever I made links with Google Cloud it would say .run.app at the end, not .cloudshell.dev

I'm not sure if the way you did it was wrong or not, but check the /outerspace/ page and see if it gives you a 404 or not

**Comment by xbubbo** [comment]
Didn't get a response for 4 days.
