### ISSUE TITLE
It won't let me open it.

### ISSUE THREAD

**Issue by woozythrower911** [InterstellarNetwork/Interstellar#281]
every time for the past 3 maybe 4 days when I try to open interstellar it says: 

This Deployment has been disabled.

Your connection is working correctly.

Vercel is working correctly.

402: PAYMENT_REQUIRED
Code: DEPLOYMENT_DISABLED
ID: sfo1::2wxc5-1699550036726-b79fed000251

If you are a visitor, contact the website owner or try again later.
If you are the owner, please [read this documentation section](https://vercel.com/docs/errors/platform-error-codes#deployment_disabled).

**Comment by EmirHat** [comment]
that's because they probably need to pay money to open the site, try other sites like hamidcc.github.io

**Comment by juniorbutyeah** [comment]
Not one of our links, can't fix this.
