### ISSUE TITLE
Website is down 

### ISSUE THREAD

**Issue by Elemperor1** [InterstellarNetwork/Interstellar#288]
Hi there,
The interstellars.games website is down. What happened

**Comment by Elemperor1** [comment]
I don't have discord, can you send me some of the links?

**Comment by Elemperor1** [comment]
How helpful, could you please just send me one of the links that are on
discord?

**Comment by Elemperor1** [comment]
Why can’t you help me?

**Comment by only2kilo** [comment]
nah thas crazy bruh

@Elemperor1 was annoying tho

**Comment by Elemperor1** [comment]
Just trying to get a link, yall are being rude for no reason

**Comment by only2kilo** [comment]
womp womp
![download](https://github.com/InterstellarNetwork/Interstellar/assets/151061790/f9ce6da8-e895-493d-9cf6-ef00bd0838b9)

**Comment by Elemperor1** [comment]
Fuck you guys

**Comment by only2kilo** [comment]
![download (1)](https://github.com/InterstellarNetwork/Interstellar/assets/151061790/b702ca74-45c3-4b9d-ac3f-2309ecc48715)
 :(

**Comment by only2kilo** [comment]
ok ill be nice 
about:blank
