### ISSUE TITLE
Apply proxy system wide

### ISSUE THREAD

**Issue by HackMeMan** [InterstellarNetwork/Interstellar#303]
I want to ask if there is a way to implement this proxy system wide using the built in proxy settings found on most operating systems. Could we list the IP in the proxy settings, or is there a way to do it using the networks tab in the browser debug tools?

**Comment by xbubbo** [comment]
The only proxy we could add would be Dynamic by Nebula which is very buggy.

**Comment by IncognitoTGT** [comment]
Wait what....oh
2 clueless people.
Just close it
