### ISSUE TITLE
How do enable WebGL on vercel?

### ISSUE THREAD

**Issue by Hamidcc** [InterstellarNetwork/Interstellar#306]
if it is not possible, can you guys tell me a site that is free and includes webgl?

**Comment by Harmomnykid** [comment]
> send a screenshot of the issue

it just shows an error saying unity not working, I cant send a screenshot now, but games like gunspin don't work

**Comment by Harmomnykid** [comment]
> send a screenshot of the issue

I'm his alt

**Comment by Hamidcc** [comment]
> Seems like a Vercel issue. There are too many of these. Stop using Vercel.

Is there any other app? That is also free?

**Comment by IncognitoTGT** [comment]
GitHub Codespaces, self host, hop, render.

**Comment by xbubbo** [comment]
This is a vercel issue not an *us* issue.

**Comment by SchoolTARMaster** [comment]
Use github codespaces. Instructions are easy and no problem.
