### ISSUE TITLE
Now.gg CSS not working

### ISSUE THREAD

**Issue by Hamidcc** [InterstellarNetwork/Interstellar#307]
is there a way to fix this? srry i put so many issues

**Comment by IncognitoTGT** [comment]
I know this issue.
Website is messed up a little  but you can still play games in it though.

**Comment by IncognitoTGT** [comment]
![Screenshot 2023-12-04 at 23 48 40](https://github.com/InterstellarNetwork/Interstellar/assets/72108630/c22e065b-644b-4c0a-ab6f-218ed8f31dab)
Zooming out. And then renders somehow. Gonna try to replicate in titaniumnetwork-dev/Ultraviolet-App

**Comment by Harmomnykid** [comment]
ok

**Comment by xbubbo** [comment]
Use Nowgg.nl from the apps or games page.
