### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by krazykrishi47** [InterstellarNetwork/Interstellar#314]
It is really annoying to have to follow these many steps just to get an unblocker. I understand this is for safety issues but it would be good if it was more accessible.

**Comment by geichelb3512** [comment]
there are pre-made links on discord.gg/interstellar

**Comment by krazykrishi47** [comment]
How did you do that?

**Comment by IncognitoTGT** [comment]
See the readme

**Comment by xbubbo** [comment]
Join our discord for links.
> https://discord.gg/interstellar
