### ISSUE TITLE
Interstellar not working on heroku

### ISSUE THREAD

**Issue by Roswe11m** [InterstellarNetwork/Interstellar#319]
Hello, I have recently tried to host this on Heroku and it has not worked. It says that the app is built and can be viewed but when you go to look at it, there is an error. Can anyone help? The link to it is https://unblox-c169f88f09ff.herokuapp.com/
![Screenshot 2023-12-09 202926](https://github.com/InterstellarNetwork/Interstellar/assets/114118472/37250323-4c36-41a8-a1b3-e9a6d730d6ba)

**Comment by Roswe11m** [comment]
I was hoping that V5.1 would fix this issue but it did not.

**Comment by IncognitoTGT** [comment]
What are the logs?

**Comment by Roswe11m** [comment]
![image](https://github.com/InterstellarNetwork/Interstellar/assets/114118472/859560e6-e006-47d0-89c6-9c9e38710d50)
![image](https://github.com/InterstellarNetwork/Interstellar/assets/114118472/70f4c3d0-67fa-4d85-b443-a94c3c237d16)

**Comment by IncognitoTGT** [comment]
That has no errors...
What are the config options?

**Comment by Roswe11m** [comment]
what do you mean by "config options"?

**Comment by IncognitoTGT** [comment]
Like do you get options for building the software?
Try docker if it doesn't work

**Comment by Roswe11m** [comment]
I dont get any config options when building it. Also what exactly is docker? I have heard of it but I am not very familiar with it.

**Comment by IncognitoTGT** [comment]
Basically it’s this containerization thing. Kinda like a VM but not exactly. Try to use that.

**Comment by Roswe11m** [comment]
Sorry for the late response, but what exactly should I do with docker?

**Comment by IncognitoTGT** [comment]
Are there any logs?

**Comment by Roswe11m** [comment]
I joined the discord. Also, the original v5.0 version was working with heroku.

**Comment by IncognitoTGT** [comment]
What is your discord username?
