### ISSUE TITLE
Interstellar no work in koyeb

### ISSUE THREAD

**Issue by TheRicePot** [InterstellarNetwork/Interstellar#332]
it just error loops
![image](https://github.com/InterstellarNetwork/Interstellar/assets/114596831/ce2cfcf4-7d37-4794-89be-9637e84360e9)

**Comment by IncognitoTGT** [comment]
What does it say in the deployment settings?
Join discord.gg/interstellar

**Comment by TheRicePot** [comment]
nevermind it works.
