### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SchoolTARMaster** [InterstellarNetwork/Interstellar#336]
# My Feedback On The Proxy
This proxy is the best one I found (probably starred it)!
I never used GitHub codespaces before, but they were good here when it comes to free hosting, specifically proxies !
10/10, anyways, and biggest thanks to the creators, you just saved my school life without having to do anything risky or damaging to my device. 🥹🥹🥹🥹🥹🥹🥹🥹🥹🥹🥹🥹🥹🥹

**Comment by xbubbo** [comment]
Appreciate the feedback, @SchoolTARMaster but this is off-topic.

For future reference, do not open an issue to not say an issue.
