### ISSUE TITLE
[Bug] can't deploy to Railway

### ISSUE THREAD

**Issue by KanekiHits** [InterstellarNetwork/Interstellar#354]
When I tried to deploy to Railway, it said banned dependency ultraviolet, please fix this

**Comment by bruhwhyamisobad** [comment]
> > > > We do not support deploying to railway.
> > 
> > 
> > > > Why is that, either way is there a way to
> > 
> > 
> > ~we're lazy~
> > fine, try deploying https://github.com/AnnotateHQ/Interstellar
> 
> It says application failed to respond

You need to specify the port using the variable “Port = 8080” (I don’t recommend deploying to railway since the trial plan only gives you a one time amount of 5 dollars)
