### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 2212312312322132** [InterstellarNetwork/Interstellar#359]
when ever i try to do something it says RangeError: Failed to construct 'Response': The status provided (0) is outside the range

**Comment by xbubbo** [comment]
> when ever i try to do something it says RangeError: Failed to construct 'Response': The status provided (0) is outside the range

What link are you using?

What blocker do you have?

**Comment by ErrorBot1122** [comment]
**I had this same [issue](https://github.com/InterstellarNetwork/Interstellar/issues/348#issuecomment-1881794314)!**

*(the second [GRAY Button](https://github.com/InterstellarNetwork/Interstellar/issues/348#issuecomment-1883446893) not the green one **[v]**)*
> Respond to the application popup by clicking "Make public."

**Comment by xbubbo** [comment]
Never got a response.
