### ISSUE TITLE
now.gg roblox issue dose not work shows a big white magnifly glasses

### ISSUE THREAD

**Issue by ksakda** [InterstellarNetwork/Interstellar#364]
**now.gg roblox**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

- Device: [Ex. Chromebook, iPad, etc.]
- OS [Ex. ChromeOS, Windows, iOS
- Browser [Ex. Chrome, Safari]

**Additional context**

**Comment by IncognitoTGT** [comment]
CSS on now.gg is broken.

**Comment by randomperson1938** [comment]
Ye

**Comment by ksakda** [comment]
ok when is it going to be ready to use

**Comment by xbubbo** [comment]
This how now been fixed.

**Comment by ksakda** [comment]
hi are you sure

**Comment by ksakda** [comment]
it dose not work for me roblox now.gg or the alternative neither work
