### ISSUE TITLE
[Bug] Retro Bowl Black Screen

### ISSUE THREAD

**Issue by ineedgamelinkstheygetblockedfast** [InterstellarNetwork/Interstellar#369]
I've been always playing retro bowl and it was normal but since yesterday when I open it its just a black screen and I let it sit for like 10 min and it was still black I don't know if its just me or a bug.

**Comment by xbubbo** [comment]
> I've been always playing retro bowl and it was normal but since yesterday when I open it its just a black screen and I let it sit for like 10 min and it was still black I don't know if its just me or a bug.

On all links or just certain ones?

**Comment by xbubbo** [comment]
> > I've been always playing retro bowl and it was normal but since yesterday when I open it its just a black screen and I let it sit for like 10 min and it was still black I don't know if its just me or a bug.

**Fixed on all links**. If it's still not working then [Clear your cache.](https://support.google.com/accounts/answer/32050)
