### ISSUE TITLE
[Bug] Codespace fails to find a file which causes it to not open the port.

### ISSUE THREAD

**Issue by Nightengale537** [InterstellarNetwork/Interstellar#375]
**Describe the bug**
Codespace failed to find a package to run the site through the npm start command and did not open to port.

**To Reproduce**

1. Make a new codespace off of the Interstellar Github
2. Run npm i && npm run start
3. behold your error
(May not be reproducible given I've only tested it on one system.)

**Expected behavior**
Codespace opens a port and makes a link to the site.

**Screenshots**
![Screenshot 2024-01-16 6 13 19 PM](https://github.com/InterstellarNetwork/Interstellar/assets/115326523/197643be-c4e8-481f-bcf1-4d9561a29fc1)

- Device: Chromebook
- OS: ChromeOS
- Browser Chrome

**Comment by IncognitoTGT** [comment]
Delete your codespace and try again. This issue cannor be reproduced by me.

**Comment by xbubbo** [comment]
> Delete your codespace and try again. This issue cannot be reproduced by me.

@Nightengale537 Follow his directions, I'm closing this issue now.

**Comment by v-5x** [comment]
Yeah I wasn't able to reproduce this issue

**Comment by Nightengale537** [comment]
Suppose it may have been an error on my part or alternatively it was just freaking out either way making a new codespace got it to work. Thank you for your time and effort.
