### ISSUE TITLE
[Bug] Github Codespaces issues

### ISSUE THREAD

**Issue by Sefpiser** [InterstellarNetwork/Interstellar#377]
When using a Github Codespaces website, games and apps do not load. 

Create a Github Codespace and run necessary commands to open the website, and load any game or app. 

A message that says "RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]."

- Chromebook
- ChromeOS
- Chrome

**Comment by IncognitoTGT** [comment]
Make sure you click the ports tab on the bottom, right click, and make sure visibility's set to "Public"

**Comment by xbubbo** [comment]
You didn't follow the instructions, it clearly says to click the make "Public" button.
