### ISSUE TITLE
Roblox is now broken can you fix this please

### ISSUE THREAD

**Issue by ksakda** [InterstellarNetwork/Interstellar#380]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**

- Device: [Ex. Chromebook, iPad, etc.]
- OS [Ex. ChromeOS, Windows, iOS
- Browser [Ex. Chrome, Safari]

**Additional context**

**Comment by ksakda** [comment]
shows a white magnifly screen

**Comment by IncognitoTGT** [comment]
This has been fixed in the latest update.

**Comment by ksakda** [comment]
![Screenshot 2024-01-18 10 20 04 PM](https://github.com/InterstellarNetwork/Interstellar/assets/156483543/aee8191d-f31a-4d60-812f-20536c83b134)
it shows this

**Comment by ksakda** [comment]
and this
![Screenshot 2024-01-18 10 21 13 PM](https://github.com/InterstellarNetwork/Interstellar/assets/156483543/0e2da407-c798-427a-ba28-50dd7ae16135)

**Comment by IncognitoTGT** [comment]
That's not Interstellar, that's Astroid, which is different.

**Comment by ksakda** [comment]
Did you see the first one 
![Uploading Screenshot 2024-01-18 10.20.04 PM.png…]()

**Comment by IncognitoTGT** [comment]
It's actually not an issue with Interstellar itself anyways. I get the same issue too. Try to go to
https://now.gg/iframe/snippet?app_pkg=com.roblox.client&partner=gamenora 


![Screenshot 2024-01-19 at 09 07 28](https://github.com/InterstellarNetwork/Interstellar/assets/72108630/b6ea2b15-c708-438d-9178-eb4abcc1e0b3)

**Comment by xbubbo** [comment]
Fixed.
