### ISSUE TITLE
instagram is now on now.gg hopefully you can add it to apps on website please thank you

### ISSUE THREAD

**Issue by ksakda** [InterstellarNetwork/Interstellar#381]
**What is the name of the game?**instagram
Provide the name of the game.

**What is the link to the game?**now.gg
Include the direct link to the game, ensuring it is a specific URL (Ex. crazygames.com/Game, coolmathgames.com/Game). Please refrain from providing Google Search links to prevent post closure.

**What is the category of the game? [Optional]**
Specify the category of the game, such as Multiplayer, Emulator, FPS, Sports, or any relevant classification. This information is optional but can help us accurately add categories to filter the game.

**Comment by xbubbo** [comment]
Closing this because you gave **0** information. 👍
