### ISSUE TITLE
Github Codespaces not working

### ISSUE THREAD

**Issue by m-the-kidd** [InterstellarNetwork/Interstellar#382]
![image](https://github.com/InterstellarNetwork/Interstellar/assets/154742245/4adbc331-4493-489c-9094-fb24aa868c3b)
![image](https://github.com/InterstellarNetwork/Interstellar/assets/154742245/1b836dd4-24da-41fe-9c57-2bdb2b917672)
I had no popup to make the codespace public

**Comment by IncognitoTGT** [comment]
Click "Forward a Port", and then type 8080 in the box. Right click, and set visibility to public, and then go to the URL.

**Comment by IncognitoTGT** [comment]
There seems to be a github issue. I'm on MacOS and Chrome and I tried to forward a port for something else, and it also didn't work.

**Comment by xbubbo** [comment]
I'll try it out rq

**Comment by v-5x** [comment]
> The box is not popping up. @IncognitoTGT you can create a PR noting it might not work for some users stick replit in the readme idgaf

It took a second but the box popped up for me on Chrome

**Comment by v-5x** [comment]
![image](https://github.com/InterstellarNetwork/Interstellar/assets/147941590/b8fb07f1-0977-4aec-8cf1-c17bc56b9516)
![image](https://github.com/InterstellarNetwork/Interstellar/assets/147941590/0f204f0e-ab3b-4e31-94f5-c248a9ae0353)

**Comment by IncognitoTGT** [comment]
Codespaces does this sometimes

**Comment by v-5x** [comment]
Also @IncognitoTGT @m-the-kidd @VillainsRule, did any of your try to change the port in the ``index.js`` file and then port forwarding that port?

**Comment by IncognitoTGT** [comment]
I didn't test it with interstellar, but another app, but no, I did not.

**Comment by v-5x** [comment]
> I didn't test it with interstellar, but another app, but no, I did not.

Well you should test it when you get a chance, because I just tried port 8082 and it port forwarded it and it worked fine for me.

**Comment by IncognitoTGT** [comment]
It seems like a codespaces bug and it has happened to me a lot.

**Comment by m-the-kidd** [comment]
> Also @IncognitoTGT @m-the-kidd @VillainsRule, did any of your try to change the port in the `index.js` file and then port forwarding that port?

No, but I can try

**Comment by IncognitoTGT** [comment]
I just ran interstellar in codespaces and it did forward.
@xbubbo close this issue

**Comment by m-the-kidd** [comment]
> seems like i got it working... https://silver-journey-xg4rr4pxqpgfprxx-9990.app.github.dev/

Same here, maybe it was just a GitHub/Codespaces related issue, closing issue

**Comment by m-the-kidd** [comment]
Issue rose again
![image](https://github.com/InterstellarNetwork/Interstellar/assets/154742245/a0aa9e13-60b1-427a-adcb-10b0042f8bff)
![image](https://github.com/InterstellarNetwork/Interstellar/assets/154742245/32f5e22e-b5f8-44a6-b6d4-3493cb79124e)

**Comment by m-the-kidd** [comment]
No popup telling me to make it public

**Comment by xbubbo** [comment]
> No popup telling me to make it public

Follow the alternative steps in the readme.
