### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by Smokeybear19** [InterstellarNetwork/Interstellar#383]
I wouldn't say its a really big issue but i was wondering what i should deploy this to because i don't want to use vercel because after awhile it needs a payment so i was just wondering what site i should use and deploy this to.

**Comment by IncognitoTGT** [comment]
kid named codespaces:

**Comment by Smokeybear19** [comment]
I'm sorry what?

**Comment by IncognitoTGT** [comment]
Try GitHub Codespaces. Instructions are in the readme.
