### ISSUE TITLE
ReferenceError: Can't find variable: userKey When clicking an app

### ISSUE THREAD

**Issue by SupremeCake17** [InterstellarNetwork/Interstellar#389]
**Describe the bug**
When I go to a site or click an app, I get a black screen that says ReferenceError: Can't find variable: userKey.

**To Reproduce**

1. Enter a site or click an app
2. Wait for it to open
3. See error ReferenceError: Can't find variable: userKey

**Expected behavior**
It opens the app and shows that website

**Screenshots**
![IMG_3617](https://github.com/InterstellarNetwork/Interstellar/assets/132528442/40c2d083-72e8-4915-bb12-e057a4451e1f)

**Comment by xbubbo** [comment]
Will be fixed shortly.

**Comment by xbubbo** [comment]
@SupremeCake17 Fixed.

**Comment by SupremeCake17** [comment]
Thanks
