### ISSUE TITLE
Github Codespaces Deployment Not Working

### ISSUE THREAD

**Issue by varixvi** [InterstellarNetwork/Interstellar#397]
When deployed, ui and everything works perfectly fine, it's just when I try to open an app, it gives me the error "RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]."

I simply followed the given instructions on the repository, got a port running. I deployed from my personal PC (Running on Windows 10) and I get the error on ChromeOS (My school Chromebook).

**Expected behavior**
I expected Interstellar to normally work I guess?

**Screenshots**
In the screenshot below, the ui works perfectly.
![image](https://github.com/InterstellarNetwork/Interstellar/assets/125153950/98777c9c-15fd-4e01-b412-78b63dd4ecbb)

However in this one, I tried to launch an app and it gave me an error.
![image](https://github.com/InterstellarNetwork/Interstellar/assets/125153950/d0209c34-2e5d-4b19-b351-9ac9678e871c)

**Device Information (please complete the following information):**

- Device: Chromebook 11 G8 EE
- OS: ChromeOS
- Browser: Chrome

**Comment by IncognitoTGT** [comment]
Did you make the instance public?

**Comment by varixvi** [comment]
> Did you make the instance public?

I didn't, I set port visibility to public and it worked. Thanks :)
