### ISSUE TITLE
I'm not sure whether this is a bug or not

### ISSUE THREAD

**Issue by Cutaly** [InterstellarNetwork/Interstellar#398]
Maybe i'm doing something wrong, So I followed every step and managed to load into interstellar but whenever I try to search anything up like 'Discord' it will just sit on a black screen with the reload, home button, fullscreen etc. I need some help. Oh and now its saying my school blocked it.

**Comment by m-the-kidd** [comment]
Same thing, I search anything up it's stuck on a black screen.

**Comment by xbubbo** [comment]
> Maybe i'm doing something wrong, So I followed every step and managed to load into interstellar but whenever I try to search anything up like 'Discord' it will just sit on a black screen with the reload, home button, fullscreen etc. I need some help. Oh and now its saying my school blocked it.

Are you self-hosting Interstellar or using an official link?

**Comment by SoccerFan57** [comment]
I noticed similar issues "getError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]" is probably the error being displayed on the black screen itself.

**Comment by BBGSLLUMP** [comment]
same

**Comment by xbubbo** [comment]
> I noticed similar issues "getError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]" is probably the error being displayed on the black screen itself.


Maybe i'm doing something wrong, So I followed every step and managed to load into interstellar but whenever I try to search anything up like 'Discord' it will just sit on a black screen with the reload, home button, fullscreen etc. I need some help. Oh and now its saying my school blocked it.

Are you self-hosting Interstellar or using an official link?

**Comment by xbubbo** [comment]
> same

Are you self-hosting Interstellar or using an official link?

**Comment by Jimmithee** [comment]
I think the problem is you didn't make thet codespace public. If the codespace isn't public, it'll show you the range error.

**Comment by xbubbo** [comment]
> I think the problem is you didn't make the codespace public. If the codespace isn't public, it'll show you the range error.

Yeah this is most likely the issue.

**Comment by xbubbo** [comment]
I got no response so I'm closing the issue.
