### ISSUE TITLE
Proxy Not Working[Bug] 

### ISSUE THREAD

**Issue by airtagdev** [InterstellarNetwork/Interstellar#399]
Whenever I go to search up something on the proxy, the site says "Cannot POST /"

**Comment by IncognitoTGT** [comment]
Screenshot?

**Comment by xbubbo** [comment]
What link?

**Comment by airtagdev** [comment]
interstellar.hop.sh

**Comment by xbubbo** [comment]
Not an official interstellar link, also seems to be outdated.
