### ISSUE TITLE
[Bug] Discord is in Bulgarian???

### ISSUE THREAD

**Issue by MrRainbowCoding** [InterstellarNetwork/Interstellar#410]
**Describe the bug**
For some reason, when we go to Discord on the apps page, it’s in Bulgarian.
**To Reproduce**

1. Go to 'Apps'
2. Click on 'Discord’
it’s Pretty easy to catch.

**Expected behavior**
Everything will change to Bulgarian. All of the UI, everything. The WHOLE page is in Bulgarian.

**Screenshots**
I am on my iPad and my friend is on a Chromebook. This is at least happening on iOS and ChromeOS.
iPad:
![IMG_2462](https://github.com/InterstellarNetwork/Interstellar/assets/88560300/eaae6007-7686-4fa2-9c57-1a0f2d9e4af8)
Chromebook:
![IMG_1127](https://github.com/InterstellarNetwork/Interstellar/assets/88560300/fff87cb2-32ea-4d83-9ce2-9f6979b4da63)
Evidence that it is in Bulgarian:
![IMG_2464](https://github.com/InterstellarNetwork/Interstellar/assets/88560300/d3c2e971-dbf7-464d-a786-fe1d8f3c4365)

**Device Information (please complete the following information):**

- Device: Chromebook and iPad
- OS: ChromeOS and iOS
- Browser: Firefox and Chrome

**Additional context**
It is possible that to fix this problem, we move the servers to the United States and change the language to English. I wonder if everyone is encountering this bug. I am open to questions.

**Comment by IncognitoTGT** [comment]
Interstellar doesn't have servers in Bulgaria. The link you are using isn't an official one.

**Comment by SkyeGamesYT** [comment]
> Interstellar doesn't have servers in Bulgaria. The link you are using isn't an official one.

I'm running interstellar on Koyeb on a Washington DC server, I can confirm it's in Bulgarian.

**Comment by Voxxie2k** [comment]
@IncognitoTGT It is not because of the server. idk why it does that. @SkyeGamesYT Just click the white button in the top right. the rest of discord is not in bulgrarian

**Comment by SkyeGamesYT** [comment]
> Reference

Yes, just the basic discord.gg site is like that, pressing any of the buttons changes it back to english.

**Comment by xbubbo** [comment]
Seems to be an issue with unofficial links only, try switching the region of the server.

Or just use the site as normal, since @SkyeGamesYT says it will work fine once clicking the button in the top right.
