### ISSUE TITLE
Google, DuckDuckGo, Bing, and all search browsers/engines aren't working due to cloudflare

### ISSUE THREAD

**Issue by vitcostarx** [InterstellarNetwork/Interstellar#411]
When I go to open a link in a search browser, such as a website, it goes to some cloudflare grey-ish screen that says "Checking if your site connection is secure." And it just loads forever. I tried reloading, won't work.

1. Go to Google/Bing/DuckDuckGo
2. Search up any link (example: dogeminer.com)
3. Click the link

What I expected:
Load the website.

Screenshots

![IMG_1239](https://github.com/InterstellarNetwork/Interstellar/assets/153834921/fec8ba2d-8baf-4e11-ac63-ea93f89a0d2d)

Device Information:
Mobile (iPad, iOS, Safari)

**Comment by xbubbo** [comment]
Interstellar will not work with some sites that have Cloudflare enabled, the only way to fix this is to self-host on your computer or hosting on a server with a residential IP

**Comment by nomodeset3** [comment]
if you have interstellar deployed on a commercial ip (such as a hetzner vps), cloudflare will flag your ip, preventing you from accessing cloudflare protected sites. you will need to selfhost  on your own computer at home
