### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by sultan333e** [InterstellarNetwork/Interstellar#414]
when i close my laptop and then i open it the proxy dont open i have to go to codespace and do it again to work can you help me i dont want to restart the proxy because i closed my laptop hope you see this

**Comment by VicMouries** [comment]
its because when you close your laptop, you temporarily disconnect from the wifi. You can't do anything about it sadly

**Comment by xbubbo** [comment]
Yeah I have no idea what you're trying to say, can you explain your issue better?

**Comment by VicMouries** [comment]
He's saying that when he closes the lid of his laptop, his proxy stops working. IMO, its because when the computer lid closes, his wifi cuts out and the proxy cant work without internet

**Comment by xbubbo** [comment]
If you close the lid of your laptop, you disconnect from the internet and the proxy can't run without internet. 

There's not really a way to fix this
