### ISSUE TITLE
[Bug] now.gg error 3401

### ISSUE THREAD

**Issue by Its-Epsilon-Eridani** [InterstellarNetwork/Interstellar#415]
**Describe the bug**
When using now.gg, nowgg.nl, or nowgg.me from the apps, games, or going directly to the website, everything seems to work. However, if you attempt to launch an app, it loads, then stops and gives the error “ng 3401” this happens for all games, and has happened when self hosted, or hosted on vercel, render, or GitHub codespaces.

**To Reproduce**

1. Go to now.gg (any)
2. Click on any game
3. Click on play in browser

**Expected behavior**
The game will launch.

**Screenshots**
![IMG_1483](https://github.com/InterstellarNetwork/Interstellar/assets/110356853/0d641fe4-0b07-469f-afbe-7f4df2715503)

**Device Information:**

- Device: ipad 9th gen
- OS :iPadOS 17.1
- Browser: safari

**Additional context**
This used to work perfectly, but recently it hasn’t been for some reason. Also doesn’t work on my home laptops, Mac mini running xubuntu, Wii U (why not), or phone running android 14.

**attempted troubleshooting**

- Host on other services or self host (failed)
- Use different devices (failed)
- Clear website data and cookies (failed)

**Comment by xbubbo** [comment]
What link are you using?

**Comment by bruhwhyamisobad** [comment]
> What link are you using for Interstellar?

There's an Arc logo on the bottom left corner, so it's probably a community link. (Official links does not show the Arc logo, for me)

**Comment by Its-Epsilon-Eridani** [comment]
> What link are you using for Interstellar?

Hosting it on my own Vercel thing, although it’s not limited to vercel, as it happens on other things. I dont use the community links.

**Comment by Xoui** [comment]
uh if ur hosting it on vercel. I dont know if it works since its a static host so, YEAH I DONT THINK its the link it maybe be proxy? also link?

**Comment by Its-Epsilon-Eridani** [comment]
> uh if ur hosting it on vercel. I dont know if it works since its a static host so, YEAH I DONT THINK its the link it maybe be proxy? also link?

Yes, but this happens on stuff like render and codespaces.

**Comment by Xoui** [comment]
ok how can i replicate it then.

**Comment by Xoui** [comment]
d

**Comment by xbubbo** [comment]
# Did not give me a link to give an example of the issue.
There could be many factors that go into this problem, wifi, blocker, vpn, ad blocker, device, browser, and more.

Without a link to test this issue on, I cannot help you.

This doesn't happen on **any** official links.

**Comment by xbubbo** [comment]
@Its-Epsilon-Eridani

**Comment by ColdzGames** [comment]
usually wont let you run it on proxys but ive been going on it regularly and it didnt work
