### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TacoNoBurrito** [InterstellarNetwork/Interstellar#419]
**Describe the bug**
Going to https://web.snapchat.com still gets flagged by Securly even whilst using proxy.

**To Reproduce**

1. Open link https://web.snapchat.com
2. Proxy gets blocked by securly under link https://accounts.snapchat.com

**Expected behavior**
Lets me go to https://web.snapchat.com without getting blocked.

**Screenshots**

**Device Information (please complete the following information):**

- Device: Chromebook (HP edu)
- OS: ChromeOS
- Browser: Chrome

**Additional context**

**Comment by xbubbo** [comment]
Snapchat doesn't work on the proxy.
