### ISSUE TITLE
Proxy is slow

### ISSUE THREAD

**Issue by OrangeThunderFire** [InterstellarNetwork/Interstellar#425]
The proxy is slow, I was trying to go onto brainly.com but it didn't even work, it kept saying reload the page.

I expect it to load and show what I want it to show
![image](https://github.com/InterstellarNetwork/Interstellar/assets/153311739/328be5aa-1352-46d0-9e4a-445dfaa0f499)

Chromebook
My browser is chrome

**Additional context**

**Comment by yet66** [comment]
First the proxy isn't slow and second you can't go to brainly.com because cloudflare blocks proxies

**Comment by xbubbo** [comment]
The proxy is **not** slow.

You cannot visit this site due to a [Cloudflare Block](https://seonorth.ca/cloudflare/blocking/).
