### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by newlazer837** [InterstellarNetwork/Interstellar#428]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] you should add pastel color themes because the copy link for theme thing doesent work

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xbubbo** [comment]
# Pointless.
You have been blocked from commenting and making posts under this org.
