### ISSUE TITLE
Unable to, well, do anything, really [Bug] 

### ISSUE THREAD

**Issue by GooseGooseDuck198** [InterstellarNetwork/Interstellar#430]
**Describe the bug**
So I normally use a specific link to access this, but recently it has been down (not giving specifics because I don't wanna get banned).
Because of this outage, I decided I would host it locally.
I opened it in Codespaces, following the tutorial in `README.MD`, and opened it on `localhost:8000`
It opened normally, but upon trying to:
1. Search anything
2. Play any game
3. Open any app

I got a blank screen with the following error:
`RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].`

Nothing showed up in the console, but this happens every time.

**To Reproduce**

1. Follow the tutorial in `README.MD` to open and run in Codespaces
2. After running it, click on the popup to open `localhost:8000`
3. Click on any tab (Games, Apps, etc)
4. Click on any app/game.
5. See error

**Expected behavior**
I should be able to play a game/run the app

**Screenshots**
![Screenshot 2024-02-07 6 36 27 PM](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/1b58ada6-932e-446d-8cd7-ffe9809e3918)
![Screenshot 2024-02-07 6 36 49 PM](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/cd5a0dca-5bf0-4b50-aba3-cd1a3485d997)
![Screenshot 2024-02-07 6 37 17 PM](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/7494671a-32cf-4131-ab46-fb5dd72ec757)

**Device Information (please complete the following information):**

- Device: Chromebook
- OS: ChromeOS
- Browser: Google Chrome

**Additional context**
I have the free version of Codespaces, and have some extensions that affect my Chromebooks ability to run some file extensions and applications.

**Comment by IncognitoTGT** [comment]
Did you set codespace visibility to public?

**Comment by GooseGooseDuck198** [comment]
@IncognitoTGT No I did not, thanks, that did work!
