### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Xoui** [InterstellarNetwork/Interstellar#431]
Hello, although you are going to say, just go look at the code how did you implement the routes? like for example games is like /ocean/ for example? i have tried to do this with express but i have failed. pls help

**Comment by xbubbo** [comment]
> Hello, although you are going to say, just go look at the code how did you implement the routes? like for example games is like /ocean/ for example? i have tried to do this with express but i have failed. pls help

Games has not been /ocean for quite some time, but  for routes you can check out [index.js](https://github.com/InterstellarNetwork/Interstellar/blob/main/index.js) to see how we did our routes.

Also, check out these docs [Express Routes - Mozilla](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes).

**Comment by Xoui** [comment]
@xbubbo  thx so much
