### ISSUE TITLE
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

### ISSUE THREAD

**Issue by HellTekky2** [InterstellarNetwork/Interstellar#438]
**Describe the bug**
"RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]."
**To Reproduce**

1. Go to any link
2. Click on any app
3. wait a minute or two

**Expected behavior**
Expected discord to load up
**Screenshots**
![image](https://github.com/InterstellarNetwork/Interstellar/assets/94703271/9bfcfaa4-ab12-432e-b024-efcfe72d7531)

**Device Information (please complete the following information):**

- Device: Chromebook
- OS ChromeOS
- Browser chroe
**Additional context**

**Comment by Xoui** [comment]
uh, hold on what do you mean by wait 2 minutes?

**Comment by xbubbo** [comment]
@HellTekky2 Clear your cache using https://support.google.com/accounts/answer/32050 and let me know if that fixes it.
