### ISSUE TITLE
[Bug] now.gg error ng3401

### ISSUE THREAD

**Issue by UltraCoolKidTime** [InterstellarNetwork/Interstellar#443]
**Describe the bug**
If you try and play a game on nowgg it doesn’t do it and throws this error
**To Reproduce**

1. Go to now.gg
2. Click on any game
3. Click on 'press play in browser'

**Expected behavior**
The game should launch
**Screenshots**
![IMG_1503](https://github.com/InterstellarNetwork/Interstellar/assets/149423019/bb050dd7-fb38-4667-b343-b967c85fa166)

**Device Information (please complete the following information):**

- Device: iPad 9th gen (school issued)
- OS: ipadOS
- Browser: safari
- Link:  https://interstellar-olive.vercel.app (Ik Vercel sucks, its just convenient for me)

**Additional context**
Also happens on my personal chromebook, plus windows laptop. Couldn’t find anything about this issue anywhere, except for an abandoned issue. Happens when using every hosting method in the discord. Used to work perfectly on all devices.

Thanks in advance!

**Comment by Xoui** [comment]
nowgg error. not yours

**Comment by UltraCoolKidTime** [comment]
> nowgg error. not yours

What does that mean?

**Comment by VicMouries** [comment]
It means you cant fix it. it is a problem with Now.GG

**Comment by xbubbo** [comment]
This is not an Interstellar issue, I tested now.gg on my own Vercel link and it works fine.

This is most likely an internet/blocker issue. 

Although, it could potentially be a Now.GG issue so maybe reach out to their support team.

**Comment by UltraCoolKidTime** [comment]
> This is not an Interstellar issue, I tested now.gg on my own Vercel link and it works fine.
> 
> This is most likely an internet/blocker issue.
> 
> Although, it could potentially be a Now.GG issue so maybe reach out to their support team.

All right, thanks.
