### ISSUE TITLE
[Bug] Chrome new rules.

### ISSUE THREAD

**Issue by pretzer25** [InterstellarNetwork/Interstellar#444]
**Describe the bug**

Because of googles new rules, you cannot use ultraviolet in iframe without same  origin
**To Reproduce**
go to site and go to a url

**Expected behavior**
it should work
**Screenshots**

**Device Information (please complete the following information):**
Chromebook
Chrome OS
Chrome
- Device: [Ex. Chromebook, iPad, etc.]
- OS [Ex. ChromeOS, Windows, iOS
- Browser [Ex. Chrome, Safari]

**Additional context**

**Comment by Xoui** [comment]
@pretzer25  how du assign ppl

**Comment by juniorbutyeah** [comment]
What is this? This is a useless issue.

**Comment by pretzer25** [comment]
well, the PROXY DOESNT WORK

**Comment by bruhwhyamisobad** [comment]
> well, the PROXY DOESNT WORK

Wdym it doesn't work 💀

**Comment by xbubbo** [comment]
> What is this? This is a useless issue.

If you have an iframe of Interstellar that isn't from the same origin as Interstellar the proxy will not work

Which is not really my problem lmao

**Comment by xbubbo** [comment]
Just tested this, it works fine in an external iframe so I'm not sure what you're talking about.

**Comment by Xoui** [comment]
yapper
