### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GameDev2022** [InterstellarNetwork/Interstellar#454]
I am having issues with password protection and am not getting a login prompt

**Comment by xbubbo** [comment]
> I am having issues with password protection and am not getting a login prompt

How are you hosting the site?

Also send me the contents of your ``config.js`` file.

Additionally, are you willing to post the link here so I can test it?

**Comment by GameDev2022** [comment]
I’m hosting it on GitHub

**Comment by GameDev2022** [comment]
Dev is https://ideal-robot-rvvpj5gpp4ghxv5j.github.dev/

**Comment by GameDev2022** [comment]
How am I supposed to set up config.js exactly?

**Comment by GameDev2022** [comment]
I set it back to default so I could start from the top

**Comment by xbubbo** [comment]
@GameDev2022 

Just pushed an update that fixed this, https://github.com/InterstellarNetwork/Interstellar/commit/823cc4d77f10da262c44a9c9f58a9fcc83301cef. 

Let me know if you have any more issues.
