### ISSUE TITLE
[Bug]  now.gg doesn't work on codespaces

### ISSUE THREAD

**Issue by iceomerbear** [InterstellarNetwork/Interstellar#465]
**Describe the bug**
When attempting to go on now.gg with codespaces, now.gg says "getting your game ready" for a moment, then turns into a static site.

**To Reproduce**

1. Use the proxy, and go to google.com. Type "<insert now.gg game title here> now.gg"
2. Click on the link that pops up
3. See error

**Expected behavior**
Should load.

**Screenshots**
![Screenshot 2024-02-20 7 58 30 AM](https://github.com/InterstellarNetwork/Interstellar/assets/111690769/aadcf7be-8791-4568-ac69-c4548102045b)

**Device Information (please complete the following information):**

- Device: Chromebook
- OS: Chrome OS
- Browser: Chrome 

**Additional context**
I use codespaces.
This same problem happens to reddit: the page unexpectedly becomes static and unusable after a moment.

**Comment by xbubbo** [comment]
Visiting now.gg directly will not work at all, use nowgg.me or find the direct link to the app/game for now.gg and then proxy it.
