### ISSUE TITLE
Interstellar proxy does not load captcha's

### ISSUE THREAD

**Issue by Zboss12** [InterstellarNetwork/Interstellar#468]
Interstellar proxy does not load captcha's

1. Go to https://diep.io (on interstellar)
2. Keep refreshing until it gives you the captcha (it will usually popup immediately)
3. The screen should say "Please validate that you are not the terminator", "You shall not pass (unless you are human)",  "I spy with my little eye" or something related 
4. The captcha will not load (it will just be blank)

I have tested this on Mac and Windows.

The captcha is supposed to load (try it out by going to diep.io without a proxy).  I have tried this with Metallic proxy (https://github.com/cognetwork-dev/Metallic) and it was able to load the captcha (it may take a couple of minutes). Could you take a look at the code and try to fix this?

**Comment by xbubbo** [comment]
Will be pushing an update to fix this later today.

**Comment by GooseGooseDuck198** [comment]
This is the same with Chrome (Browser and OS)

**Comment by Zboss12** [comment]
Metallic proxy uses ultraviolet and works with the captcha

**Comment by xbubbo** [comment]
This has been fixed, use the window popout button on the proxy page which will open another window and keep your ability to use captchas while staying cloaked.
