### ISSUE TITLE
[Bug] Geforce Now

### ISSUE THREAD

**Issue by dgvlevacy** [InterstellarNetwork/Interstellar#472]
go to  apps, search "geforce now", make a account or sign in to your account, click any game when it gets to your spot to play it brings up an error.

**Comment by ooxcrimson** [comment]
the error means your school is blocking the connection to geforce now servers which cant be fixed

**Comment by xbubbo** [comment]
What's the error?

**Comment by Xtendera** [comment]
> the error means your school is blocking the connection to geforce now servers which cant be fixed

This is incorrect, this is a proxy, and the point of a proxy is to tunnel that blocked traffic through different servers. @dgvlevacy if you can show the error, that would be great. Just keep in mind this might be an Ultraviolet error, not an interstellar error, so you should probably report it there.

**Comment by ooxcrimson** [comment]
> > the error means your school is blocking the connection to geforce now servers which cant be fixed
> 
> This is incorrect, this is a proxy, and the point of a proxy is to tunnel that blocked traffic through different servers. @dgvlevacy if you can show the error, that would be great. Just keep in mind this might be an Ultraviolet error, not an interstellar error, so you should probably report it there.

this also happens with now.gg so this is not a ultraviolet issue

**Comment by T1moraa** [comment]
Hello, indeed, geforce is having problems right now, I use my home computer via home Wi-Fi, when you log into geforce using the interstellar proxy, geforce starts without any problems, but when I log into any game, I get in line, and when the queue reaches me, the download begins after that, geforce now itself has an error with the code 0x00000157, this error says that you need to check your Internet connection.

**Comment by T1moraa** [comment]
> What's the error?

Hello, indeed, geforce is having problems right now, I use my home computer via home Wi-Fi, when you log into geforce using the interstellar proxy, geforce starts without any problems, but when I log into any game, I get in line, and when the queue reaches me, the download begins after that, geforce now itself has an error with the code 0x00000157, this error says that you need to check your Internet connection.

**Comment by Xtendera** [comment]
> > What's the error?
> 
> Hello, indeed, geforce is having problems right now, I use my home computer via home Wi-Fi, when you log into geforce using the interstellar proxy, geforce starts without any problems, but when I log into any game, I get in line, and when the queue reaches me, the download begins after that, geforce now itself has an error with the code 0x00000157, this error says that you need to check your Internet connection.

This is interesting. Again, my interstellar server is fine, I was able to log on to fortnite, bloons TD 6, and Phasmophobia perfectly, that too at school.

**Comment by T1moraa** [comment]
> > > What's the error?
> > 
> > 
> > Hello, indeed, geforce is having problems right now, I use my home computer via home Wi-Fi, when you log into geforce using the interstellar proxy, geforce starts without any problems, but when I log into any game, I get in line, and when the queue reaches me, the download begins after that, geforce now itself has an error with the code 0x00000157, this error says that you need to check your Internet connection.
> 
> This is interesting. Again, my interstellar server is fine, I was able to log on to fortnite, bloons TD 6, and Phasmophobia perfectly, that too at school.

Wow, It's unexpected, I thought it was the same for everyone.

**Comment by T1moraa** [comment]
> > > What's the error?
> > 
> > 
> > Hello, indeed, geforce is having problems right now, I use my home computer via home Wi-Fi, when you log into geforce using the interstellar proxy, geforce starts without any problems, but when I log into any game, I get in line, and when the queue reaches me, the download begins after that, geforce now itself has an error with the code 0x00000157, this error says that you need to check your Internet connection.
> 
> This is interesting. Again, my interstellar server is fine, I was able to log on to fortnite, bloons TD 6, and Phasmophobia perfectly, that too at school.

Are you using last version of interstellar?

**Comment by Xtendera** [comment]
> Are you using last version of interstellar?

Yep, pulled straight from git on saturday

**Comment by IncognitoTGT** [comment]
Every proxy has that error what are you yapping about

In fact, I actually use Interstellar's backend stuff with other proxies

**Comment by OrangeThunderFire** [comment]
no I play geforce I have proxies that can run it better than the original
one.

**Comment by Xtendera** [comment]
> just use a faster proxy, almost every proxy is faster than interstellar, but the new astro one might be good.

... Dude once you load the iframe speed the speed of the app itself is irrelevent, only about how fast the servers themselves are.

**Comment by OrangeThunderFire** [comment]
idk man the proxy I use is faster

**Comment by Xtendera** [comment]
> idk man the proxy I use is faster

Yeah... Bcs the server is faster. If you host an interstellar instance on the same server, it would perform the same.

**Comment by OrangeThunderFire** [comment]
maybe yall should not use ultraviolet and make your own
