### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [InterstellarNetwork/Interstellar#478]
**Describe the bug**
Can't run with node index.js or npm run start

**To Reproduce**

1. Use aaPanel to start it once (i used 90 port first on accident)
2. Start it again (i set port to 8080)
4. See "Failed to start"

**Expected behavior**
It to start.

**Screenshots**
![image](https://github.com/InterstellarNetwork/Interstellar/assets/75588579/bc2ea29d-3025-4de0-8ca3-d89b496bdb2b)

**Device Information (please complete the following information):**

- Device: VPS
- OS: Ubuntu
- Browser: SSH / Firefox

**Comment by xbubbo** [comment]
Update NodeJS/Npm like Airtag said, and if that doesnt fix it open another issue.
