### ISSUE TITLE
[Bug] Random pop ups

### ISSUE THREAD

**Issue by Esbalt** [InterstellarNetwork/Interstellar#482]
**Describe the bug**
So basically whenever I go on it on my school iPad, it has a bunch of fake pop up’s appear that say things like “Install VPN”. It’s not just one link, I tested several. The proxy also just doesn’t load, it’s just a white screen.

**To Reproduce**
Go to any interstellar link on iPad
Wait a second, and they will start popping up.

**Expected behavior**
Random scam pop ups shoulden’t appear.

**Screenshots**

![IMG_3362](https://github.com/InterstellarNetwork/Interstellar/assets/160613350/bedbfdc3-fe13-4e6f-9fcd-fef94a57849d)
![IMG_3361](https://github.com/InterstellarNetwork/Interstellar/assets/160613350/aaa500c4-766f-4270-942b-3debda983da2)

![IMG_3364](https://github.com/InterstellarNetwork/Interstellar/assets/160613350/2db767c3-a2d5-4517-ba4f-39a360c84607)

**Device Information (please complete the following information):**

- Device: iPad 8th gen
- OS: iOS
- Browser: Safari

**Comment by Esbalt** [comment]
Another one: 
![IMG_3366](https://github.com/InterstellarNetwork/Interstellar/assets/160613350/9b2b150e-d629-4335-9120-6432cfa0c7a4)

**Comment by Esbalt** [comment]
Also, none of the games work.

**Comment by yet66** [comment]
They added ads to interstellar to pay for hosting that's why those ads appear

**Comment by xbubbo** [comment]
Click x on the popups, I pay over $105 per month on hosting the site.

There isn't very many ad providers who will accept a proxy site and pay well, this is really my only option right now.

Just click x on the popups, and also the games work fine.

**Comment by Xoui** [comment]
@xbubbo  105???? what specs does it have. I'm thinking of self hostig so I don't have to push changes every day

**Comment by IncognitoTGT** [comment]
just use oracle cloud free lol

**Comment by MadjikDotPng** [comment]
> Click x on the popups, I pay over $105 per month on hosting the site.
> 
> There isn't very many ad providers who will accept a proxy site and pay well, this is really my only option right now.
> 
> Just click x on the popups, and also the games work fine.

We need to come up with a better ad provider.

**Comment by Esbalt** [comment]
It’s still showing them, how long will it be until the commit applies?
