### ISSUE TITLE
[Feature] Add rammerhead proxy

### ISSUE THREAD

**Issue by Zman1234567** [InterstellarNetwork/Interstellar#496]
**Is your feature request related to a problem? Please describe.**
Rammerhead is a fast proxy that works extremely well for most websites (including now.gg out of the box and hornex.pro). It is a lot faster in most cases than ultraviolet and allows sessions. 

**Describe the solution you'd like**
A couple of proxies have implemented Rammerhead. The dev branch of [Metallic](https://github.com/cognetwork-dev/Metallic/tree/dev) and the main branch of [Nebula](https://github.com/NebulaServices/Nebula) are both examples of this.

**Describe alternatives you've considered**
Rammerhead supports lots of websites that ultraviolet does not support, and vice versa. Having an option to pick between the two will add much more support for additional websites.

**Comment by pretzer25** [comment]
then many sites would get unfunctional

**Comment by xbubbo** [comment]
Most likely not going to happen, rammerhead is very annoying to implement

**Comment by IncognitoTGT** [comment]
It will make your codebase very nice :fire:
