### ISSUE TITLE
[Bug] Cannot deploy with cyclic or koyeb

### ISSUE THREAD

**Issue by Esbalt** [InterstellarNetwork/Interstellar#497]
**Describe the bug**
When you try to host it on koyeb, it runs out of free storage space
When you try to host it on cyclic, it says that it’s against its tos to use proxy’s…

Does anybody have a way to bypass this?

**Comment by OrangeThunderFire** [comment]
Use codesandbox or vercel.

**Comment by Esbalt** [comment]
Yup, vercel works
