### ISSUE TITLE
Opening apps does not work

### ISSUE THREAD

**Issue by izerimriw** [InterstellarNetwork/Interstellar#498]
Every time I open an app it says "The Web page at " " might be temporarily down or it may have moved permanently to a new web address." How can i fix this?

**Comment by Zman1234567** [comment]
The same is happening for me even when I search on the proxy
![Screenshot](https://github.com/InterstellarNetwork/Interstellar/assets/162124909/988cf9b4-d54d-4c1c-82bb-68f616971014)

**Comment by xbubbo** [comment]
What link are you using?
@Zman1234567

**Comment by Zman1234567** [comment]
I am running it locally. I just searched up hello, but I also tried accessing google.com

**Comment by izerimriw** [comment]
I also did the same, i have no clue what is going on.

**Comment by xbubbo** [comment]
I believe I have fixed it, Try now.

@izerimriw @Zman1234567

**Comment by Swampgoat4** [comment]
> I believe I have fixed it, Try now.
> 
> @izerimriw @Zman1234567

It is still broken for me, for whatever reason.

**Comment by Swampgoat4** [comment]
Do I have to do some extra steps to get it to work? 
![image](https://github.com/InterstellarNetwork/Interstellar/assets/162386228/fdda1bd0-26b6-4953-a4b9-d294628039db)

**Comment by xbubbo** [comment]
Fixed
