### ISSUE TITLE
[Bug] While on school network it does not work at all.

### ISSUE THREAD

**Issue by Esbalt** [InterstellarNetwork/Interstellar#500]
The title says it all. It works on my pc at home, but not on any school devices.

**Comment by girty7777** [comment]
same

**Comment by Zman1234567** [comment]
It does not work on my Mac

**Comment by Esbalt** [comment]
Oh and one more thing it worked a little bit ago, but now it doesn’tOn Mar 5, 2024, at 4:49 PM, girty7777 ***@***.***> wrote:﻿
same

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

(This transmittal and/or attachments have been sent from a
student of the North Allegheny School District)

**Comment by MadjikDotPng** [comment]
You are being very vague? What happens when you try to go to Interstellar? Is it blocked by GoGuardian, Securly, etc?

**Comment by Esbalt** [comment]
> You are being very vague? What happens when you try to go to Interstellar? Is it blocked by GoGuardian, Securly, etc?

It’s kind of weird, it just shows a white screen. Example: 
![IMG_3393](https://github.com/InterstellarNetwork/Interstellar/assets/160613350/58f0f8b0-0965-4211-b499-6adf7ec0774c)

**Comment by MadjikDotPng** [comment]
It makes it a lot harder to diagnose due to you being on iPad

**Comment by quinn22345234** [comment]
i think at the moment it is broken on ipad cause it does not work on my ipad either

**Comment by MadjikDotPng** [comment]
I'll add better mobile support to the new Interstellar Astro version.

**Comment by Esbalt** [comment]
Is that your personal iPad, or a school one? I tested on school computers and it didn’t work either. I still don’t know it it’s an iPad or network problem, but it seems like it’s the network.
-- 
(This transmittal and/or attachments have been sent from a
student of the 
North Allegheny School District)

**Comment by quinn22345234** [comment]
> Is that your personal iPad, or a school one? I tested on school computers and it didn’t work either. I still don’t know it it’s an iPad or network problem, but it seems like it’s the network. -- (This transmittal and/or attachments have been sent from a student of the North Allegheny School District)

I’m on my school Ipad.

**Comment by Esbalt** [comment]
My school iPad.

-- 
(This transmittal and/or attachments have been sent from a
student of the 
North Allegheny School District)

**Comment by MadjikDotPng** [comment]
I think it might have something to do with your network, not the device.

**Comment by tuta-amb** [comment]
probs a network block maybe?

**Comment by xbubbo** [comment]
Most likely blocked by your network, try self-hosting

**Comment by quinn22345234** [comment]
> Most likely blocked by your network, try self-hosting

How can I do that?

**Comment by MadjikDotPng** [comment]
Learn web development.
