### ISSUE TITLE
Viruses

### ISSUE THREAD

**Issue by Swampgoat4** [InterstellarNetwork/Interstellar#503]
Theres random websites popping up when I try to click stuff. Most are viruses. Actually. Like, all of them are viruses. I click on some random spot like the apps button and a pop up appears saying that my windows needs an update or something. I dont know if this was something that xbubbo did in the code that is causing malicious sites to pop up or just a bug.

**Comment by Swampgoat4** [comment]
I am also having troubles with the "Moved to a new location" issue.

**Comment by bruhwhyamisobad** [comment]
> Theres random websites popping up when I try to click stuff. Most are viruses. Actually. Like, all of them are viruses. I click on some random spot like the apps button and a pop up appears saying that my windows needs an update or something. I dont know if this was something that xbubbo did in the code that is causing malicious sites to pop up or just a bug.
> 
> 

These ads are just to pay for the servers that host Interstellar which costs over $105

**Comment by bruhwhyamisobad** [comment]
> I am also having troubles with the "Moved to a new location" issue.

This issue is being looked into by bubbo.

**Comment by Swampgoat4** [comment]
Alright
