### ISSUE TITLE
Website cropped when not in fullscreen

### ISSUE THREAD

**Issue by Zman1234567** [InterstellarNetwork/Interstellar#504]
**Describe the bug**
Website is cropped when not in full screen. 

**To Reproduce**

1. Go to https://florr.io
2. Click on "Play as guest" and play
3. The bottom part will be cropped

**Expected behavior**
I know that the navbar at the top removes a bit of the website, but would it be possible to adjust the iframe size when not in fullscreen to only take the part of the webpage remaining?

**Comment by MadjikDotPng** [comment]
Should be an easy fix, I'll go in today and fix it. I've noticed the bug myself and it is kinda annoying.

**Comment by MadjikDotPng** [comment]
No prob

**Comment by xbubbo** [comment]
Fixed
