### ISSUE TITLE
[Feature] Use Google ads

### ISSUE THREAD

**Issue by esb6** [InterstellarNetwork/Interstellar#505]
**Is your feature request related to a problem? Please describe.**
It’s really annoying how all the virus ads pop up. Google ads is more secure and these won’t be scams.

**Comment by MadjikDotPng** [comment]
I have to agree, but its up to bubbo how to monetize the website. Most normal safer ad providers don't wan't to be seen on a web proxy, so it's hard to find reliable ad providers.

**Comment by Esbalt** [comment]
> I have to agree, but its up to bubbo how to monetize the website. Most normal safer ad providers don't wan't to be seen on a web proxy, so it's hard to find reliable ad providers.

Google doesn’t really care that much, but you’re right. It’s all up to bubbo.

**Comment by xbubbo** [comment]
Google ads will not accept a proxy, so this is not going to happen. I've tried many times.
