### ISSUE TITLE
Safe Search

### ISSUE THREAD

**Issue by LordChez79** [InterstellarNetwork/Interstellar#506]
My friend recently contracted a trojan virus while using the games and other features**
*I suggest we employ safe search to keep this from happening again, because as of right now, I am having to fix peoples computers*
**And i am not a code specialist so please fix this soon. Also, many people are convinced that you are spreading and infecting peoples computers with this virus on purpose. Please tell me this is not true**

**Comment by bruhwhyamisobad** [comment]
> My friend recently contracted a trojan virus while using the games and other features**
> 
> *I suggest we employ safe search to keep this from happening again, because as of right now, I am having to fix peoples computers*
> 
> **And i am not a code specialist so please fix this soon. Also, many people are convinced that you are spreading and infecting peoples computers with this virus on purpose. Please tell me this is not true**
> 
> 

These ads are just to pay for the servers that host Interstellar which costs over $105. Just click the "X" in the corner or close button (button is different on each ad) to close a ad. If you accidentally clicked an ad and it redirects to a website, just close the tab.

**Comment by xbubbo** [comment]
We are not spreading viruses, they are advertisements so that I can pay for my server to host the site each month. Disable ads in settings if you are having issues.
