### ISSUE TITLE
[Bug] range error

### ISSUE THREAD

**Issue by Reaper-Gaming** [InterstellarNetwork/Interstellar#511]
it keeps giving me an error whenever I open any app. i dont know what it means or how to fix it 

here is a screenshot of the error
![Screenshot 2024-03-07 14 05 27](https://github.com/InterstellarNetwork/Interstellar/assets/158211498/a030e6fb-1441-414a-b43f-bec169cd2cea)

**Comment by Reaper-Gaming** [comment]
> > it keeps giving me an error whenever I open any app. i dont know what it means or how to fix it
> > here is a screenshot of the error
> > ![Screenshot 2024-03-07 14 05 27](https://private-user-images.githubusercontent.com/158211498/311021822-a030e6fb-1441-414a-b43f-bec169cd2cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTQ2NzIsIm5iZiI6MTcwOTg1NDM3MiwicGF0aCI6Ii8xNTgyMTE0OTgvMzExMDIxODIyLWEwMzBlNmZiLTE0NDEtNDE0YS1iNDNmLWJlYzE2OWNkMmNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMzMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDhlNmY0MGVhOTNhODRhYjAzNzljODg1MzI2NzRiZWMyNDM2NzgwMjE4NjE3OWQ5NTBmMTgwNWNlYjViOGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.urH7iKS-gf3jaVTm_AZoNcHonUGGNu9fGOFlGPk5MNg)
> 
> That's just an ultraviolet issue, not interstellar's. (Basically Interstellar can't fix this)

How do i fix it

**Comment by bruhwhyamisobad** [comment]
> > > it keeps giving me an error whenever I open any app. i dont know what it means or how to fix it
> 
> > > here is a screenshot of the error
> 
> > > ![Screenshot 2024-03-07 14 05 27](https://private-user-images.githubusercontent.com/158211498/311021822-a030e6fb-1441-414a-b43f-bec169cd2cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTQ2NzIsIm5iZiI6MTcwOTg1NDM3MiwicGF0aCI6Ii8xNTgyMTE0OTgvMzExMDIxODIyLWEwMzBlNmZiLTE0NDEtNDE0YS1iNDNmLWJlYzE2OWNkMmNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMzMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDhlNmY0MGVhOTNhODRhYjAzNzljODg1MzI2NzRiZWMyNDM2NzgwMjE4NjE3OWQ5NTBmMTgwNWNlYjViOGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.urH7iKS-gf3jaVTm_AZoNcHonUGGNu9fGOFlGPk5MNg)
> 
> > 
> 
> > That's just an ultraviolet issue, not interstellar's. (Basically Interstellar can't fix this)
> 
> 
> 
> How do i fix it?

Use another link

**Comment by Reaper-Gaming** [comment]
> > > > it keeps giving me an error whenever I open any app. i dont know what it means or how to fix it
> > 
> > 
> > > > here is a screenshot of the error
> > 
> > 
> > > > ![Screenshot 2024-03-07 14 05 27](https://private-user-images.githubusercontent.com/158211498/311021822-a030e6fb-1441-414a-b43f-bec169cd2cea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTQ2NzIsIm5iZiI6MTcwOTg1NDM3MiwicGF0aCI6Ii8xNTgyMTE0OTgvMzExMDIxODIyLWEwMzBlNmZiLTE0NDEtNDE0YS1iNDNmLWJlYzE2OWNkMmNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QyMzMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDhlNmY0MGVhOTNhODRhYjAzNzljODg1MzI2NzRiZWMyNDM2NzgwMjE4NjE3OWQ5NTBmMTgwNWNlYjViOGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.urH7iKS-gf3jaVTm_AZoNcHonUGGNu9fGOFlGPk5MNg)
> > 
> > 
> > > 
> > 
> > 
> > > That's just an ultraviolet issue, not interstellar's. (Basically Interstellar can't fix this)
> > 
> > 
> > How do i fix it?
> 
> I don't really know, but try to use another link

As in make a new codespace?

**Comment by xbubbo** [comment]
Make your codespace public.
