### ISSUE TITLE
[Feature] Fix error thrown when playing web games made in Godot

### ISSUE THREAD

**Issue by GooseGooseDuck198** [InterstellarNetwork/Interstellar#516]
When running some [play in browser] games on itch.io, an error is thrown.
This occurs when you attempt to play a game made and packaged for web by Godot.

---

This is the error thrown:

![image](https://github.com/InterstellarNetwork/Interstellar/assets/119032101/9743d02f-ff6d-440a-abcb-180f19a6a472)
Alt text:

==

The following features required to run Godot projects on the Web are missing:
Cross Origin Isolation - Check web server configuration (send correct headers)
SharedArrayBuffer - Check web server configuration (send correct headers))

==

---

This indicates the browser (interstellar) is unable to send and recive the correct packages to run Godot games.

This is not a bug or issue on, as the [feature] tag, but it is something that, if fixed, would improve the expierence.

**Comment by MadjikDotPng** [comment]
Godot isn't currently supported. Proxies mess up headers for requests so when Godot requires them and can't find them it throws an error.

**Comment by MadjikDotPng** [comment]
It's prob an issue with CORS

**Comment by xbubbo** [comment]
I'll look into this when I get a chance.

**Comment by xbubbo** [comment]
What's the link? @GooseGooseDuck198

**Comment by xbubbo** [comment]
No response.
