### ISSUE TITLE
Nothing loading!

### ISSUE THREAD

**Issue by rcpiee** [InterstellarNetwork/Interstellar#518]
Nothing will load on chrome OS

**Comment by MadjikDotPng** [comment]
Please specify your actual full issue 😭 

I can't tell whats going on when all you say is "nothing will load"

**Comment by pretzer25** [comment]
I think your js is disabled

**Comment by uhidontkno** [comment]
> Nothing will load on chrome OS

![](https://img.rare1k.dev/differenceinskill.gif)
