### ISSUE TITLE
[Feature] Youtube adblocker

### ISSUE THREAD

**Issue by Zman1234567** [InterstellarNetwork/Interstellar#533]
**Is your feature request related to a problem? Please describe.**
Youtube adblocker would be useful to watch youtube without dealing with ads.

**Describe the solution you'd like**
[Hypertabs](https://github.com/amethystnetwork-dev/Hypertabs) has an adblocker, which is extremely effective in blocking ads.

**Comment by MadjikDotPng** [comment]
Not a bad idea, but might be tricky to implement.

**Comment by MadjikDotPng** [comment]
Will look into it.
