### ISSUE TITLE
Half-screen when using Now.GG

### ISSUE THREAD

**Issue by xbubbo** [InterstellarNetwork/Interstellar#535]

**Comment by YamiYugiz** [comment]
Same problem for me

**Comment by Harlan124** [comment]
same here

**Comment by YamiYugiz** [comment]
Doesn't even work for me because of this problem
![Screenshot 2024-03-13 5 54 56 PM](https://github.com/InterstellarNetwork/Interstellar/assets/159738840/0641690c-ea11-4cbc-a4ff-14bfcf9a7248)

**Comment by IncognitoTGT** [comment]
This is a known bug with Now.GG, other proxies have been having the same problem.

**Comment by YamiYugiz** [comment]
The unsafe proxy thing?
Or the half-screen

**Comment by YamiYugiz** [comment]
> The unsafe proxy thing? Or the half-screen
![image](https://github.com/InterstellarNetwork/Interstellar/assets/159738840/a1d1ec81-54de-4460-9656-356dcc907431)
