### ISSUE TITLE
[Bug] Interstellar proxy not working on Apple devices (iOS/iPadOS 17.4)

### ISSUE THREAD

**Issue by bl4ckun1x-team** [InterstellarNetwork/Interstellar#536]
**Describe the bug**
When trying to access a website using Interstellar, the top bar appears without any URL and shows a blank page.

**To Reproduce**

1. Use an Apple mobile device running iOS or iPadOS;
2. Access Interstellar using Safari and click on any App (example: YouTube);
3. Notice that the top bar is empty (no URL) and the page stays blank.

**Expected behavior**
Be able to access websites through Interstellar’s proxy on an Apple mobile device (iOS or iPadOS).

**Screenshot**
![IMG_0788](https://github.com/InterstellarNetwork/Interstellar/assets/153548839/eb941061-f99f-4036-bc60-20a2b1b10619)

**Device Information (please complete the following information):**

- Device: iPad
- OS: iPadOS 17.4
- Browser: Safari (version coming with iPadOS 17.4)

**Additional context**
The issue started appearing when xbubbo added ads to Interstellar. Also, I use Cloudflare DNS.

**Comment by MadjikDotPng** [comment]
Apple devices do this sometimes... I don't know exactly how to fix it but I know there is a fix.

**Comment by bl4ckun1x-team** [comment]
I may also add that I use Private Browsing so my system administrator doesn’t see the websites so he doesn’t ban them through the school’s network.

**Comment by bl4ckun1x-team** [comment]
After some testing, I discovered that on my computer on Google Chrome, it does work. However, I also tried Interstellar on Safari using regular browsing mode (non-Private) and it still does not work.
If anyone has a fix, it would be highly appreciated to share it here.

**Comment by bruhwhyamisobad** [comment]
> After some testing, I discovered that on my computer on Google Chrome, it does work. However, I also tried Interstellar on Safari using regular browsing mode (non-Private) and it still does not work.
> 
> If anyone has a fix, it would be highly appreciated to share it here.

Go to settings and change your proxy to Dynamic (Update your version of Interstellar if you can't find that option)

**Comment by bl4ckun1x-team** [comment]
> > After some testing, I discovered that on my computer on Google Chrome, it does work. However, I also tried Interstellar on Safari using regular browsing mode (non-Private) and it still does not work.
> > If anyone has a fix, it would be highly appreciated to share it here.
> 
> Go to settings and change your proxy to Dynamic (Update your version of Interstellar if you can't find that option)

Does it work for you ? Because for me it doesn’t…
It worked perfectly three weeks ago and now it doesn’t work on Safari and on Firefox (non-Private).
Please check the commits to see if you’ve made an incompatibility since the “Added Ads (Test)” commit.
Thanks for helping me anyways…

**Comment by xbubbo** [comment]
I will look into this.

**Comment by xbubbo** [comment]
Just tested a month old commit (https://github.com/InterstellarNetwork/Interstellar/commit/0d4326b1591d6bef751822a25c50f3ccba35ba6c) and it did not work for ios, is there a specific commit that works that you know of?

**Comment by xbubbo** [comment]
I found a commit that is working, I am looking into it again.

**Comment by thegreatmastermind** [comment]
Same issue with me shar the commit please

**Comment by bl4ckun1x-team** [comment]
Thanks a lot, I didn’t have a lot of time to look for a possible cause this week but I found an old link that works on iOS/iPadOS

**Comment by bl4ckun1x-team** [comment]
Any news ?
Still not fixed.

**Comment by pretzer25** [comment]
try opening in the proxy link in a new tab

**Comment by bl4ckun1x-team** [comment]
Nope, doesn’t do anything…
I think this is issue is caused by the new tabs layout (the top bar).

**Comment by MadjikDotPng** [comment]
I don't think so?

**Comment by whoopdoge** [comment]
Having the same issuew

**Comment by bl4ckun1x-team** [comment]
Bug has been fixed, at least for me.
The 'Fixed for Firefox' commit fixed it for Safari too.
Thank you so much.
