### ISSUE TITLE
Koyeb Deployment Issue

### ISSUE THREAD

**Issue by amathew4538** [InterstellarNetwork/Interstellar#537]
I have been trying for some time to try to deploy to koyeb, but it just keeps failing. I believe it has something to do with pnpm and heroku, but I do not know what. 

This is what it says:

![IMG_2754](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/7b75206e-0d5c-4a9f-9a92-59bd4193c336)

![IMG_2755](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/1fa4dc0c-1671-4efa-be6c-92b582bf910f)

![IMG_2756](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/eb01bb54-86e6-4399-ad08-4f79ff0c9814)

If it could be fixed, that would be great. I did click the deploy to koyeb button by the way.

**Comment by bruhwhyamisobad** [comment]
> I have been trying for some time to try to deploy to koyeb, but it just keeps failing. I believe it has something to do with pnpm and heroku, but I do not know what. 
> 
> 
> 
> This is what it says:
> 
> 
> 
> ![IMG_2754](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/7b75206e-0d5c-4a9f-9a92-59bd4193c336)
> 
> 
> 
> ![IMG_2755](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/1fa4dc0c-1671-4efa-be6c-92b582bf910f)
> 
> 
> 
> ![IMG_2756](https://github.com/InterstellarNetwork/Interstellar/assets/121983385/eb01bb54-86e6-4399-ad08-4f79ff0c9814)
> 
> 
> 
> If it could be fixed, that would be great. I did click the deploy to koyeb button by the way.

Select the dockerfile option

**Comment by amathew4538** [comment]
What do i put for the image

**Comment by amathew4538** [comment]
Nvm

**Comment by amathew4538** [comment]
It worked! Yay!
