### ISSUE TITLE
deployment popup works but website doesn't work

### ISSUE THREAD

**Issue by Furyx407** [InterstellarNetwork/Interstellar#538]
opened codespace and followed steps website popup is working but when I search it doesn't work

opened the codespace and put in npm I && npm run start
went to website and allowed popups and went into about blank popup but when I searched it said it was out of range and codespace was still working

**Screenshots**

**Device Information (please complete the following information):**

- Device: dell chromebook
- OS Windows
- Browser Chrome
![Capture](https://github.com/InterstellarNetwork/Interstellar/assets/153039598/ea2de624-b14d-4290-ba55-e81dceacb8e2)

**Additional context**

**Comment by xbubbo** [comment]
You did not make the site public like it says to in the steps.
