### ISSUE TITLE
[Bug] Now.gg Unsafe proxy detected

### ISSUE THREAD

**Issue by Harlan124** [InterstellarNetwork/Interstellar#539]
On a laptop whenever you go to any now.gg game on any of the servers like roblox or tiktok when you load in it says Unsafe proxy detected please visit "websitesball.com" which also doesnt work. Please fix! thank you

**Comment by MadjikDotPng** [comment]
This is a common issue, I don't exactly know the fix. Are you using Ultraviolet or Dynamic as your proxy?

**Comment by Harlan124** [comment]
the defualt

**Comment by MadjikDotPng** [comment]
Can you please look? It's under Proxy on the settings page.

**Comment by Harlan124** [comment]
![image](https://github.com/InterstellarNetwork/Interstellar/assets/107516488/51db6e95-d674-432b-b7d3-4ecd033c91a4)
this is all I see in settings

**Comment by bruhwhyamisobad** [comment]
> ![image](https://github.com/InterstellarNetwork/Interstellar/assets/107516488/51db6e95-d674-432b-b7d3-4ecd033c91a4)
> 
> this is all I see in settings

You are using an older version of Interstellar

**Comment by xbubbo** [comment]
Now.gg now blocks proxies
