### ISSUE TITLE
[Bug] doesn't work 

### ISSUE THREAD

**Issue by iceomerbear** [InterstellarNetwork/Interstellar#547]
**Describe the bug**
proxy doesn't work

**To Reproduce**
do the normal stuff steps
put in the link
go back to terminal and see the error message

**Screenshots**
![image](https://github.com/InterstellarNetwork/Interstellar/assets/111690769/60212d0d-ce83-462d-a37e-4961a7320278)

**Device Information (please complete the following information):**
Chromebook

**Comment by MadjikDotPng** [comment]
sobbing

**Comment by IncognitoTGT** [comment]
sobbing here too
