### ISSUE TITLE
Ad problems.

### ISSUE THREAD

**Issue by FoundationINCCorporateTeam** [InterstellarNetwork/Interstellar#548]
Hello! I am hosting my instance of Interstellar and I am having a problem with ads. I don't have a problem with them except for 2 things and I want to know if there is a way I can solve it. 1 When people click the X button on the ads for some of them it still redirects them ( I need a solution for both of these if someone could give me a solution that would help A lot. 2 Whenever someone closes the ads right after they close them the ads open right back up like 5 sec later. There is no cooldown whatsoever. Here is a link to my repo: [REPO](https://github.com/FoundationINCCorporateTeam/Interstellar)

**Comment by FoundationINCCorporateTeam** [comment]
I have tried to disable the ads by clicking Off in settings but whenever I click it the setting doesn't save.

**Comment by MadjikDotPng** [comment]
I'll fix the settings save issue later. Ad's are indeed annoying right now and I'm hoping we can come up with a solution but in the meantime you'll just have to deal with them.

**Comment by pretzer25** [comment]
guys, just go in your code and where it says main.js in the scripts folder, on the fourth line set the true to false, clear all cookies, and retry, no more ads for anyone who goes in your website

**Comment by FoundationINCCorporateTeam** [comment]
Thanks I will try that

**Comment by FoundationINCCorporateTeam** [comment]
Seems to be working for me on my home computer but I will check with others tomorrow before closing this issue.

**Comment by FoundationINCCorporateTeam** [comment]
Ok that problem is solved but a new one arose. When I deploy commits to my vercel hosted proxy instance this is what I see. you can check it out for yourself at
URL I am having problems with: zxcvbnm.ipse.ro
URL that is doing what I want: https://interstellar-six-xi.vercel.app/
Here is some pictures from each url that are in the same project so they should look the same
zxcvbnm.ipse.ro:
![Screenshot 2024-03-18 205053](https://github.com/InterstellarNetwork/Interstellar/assets/130522379/b36df1b1-454b-4334-aa69-a1cb02d2ff52)
interstellar-six-ix.vercel.app (the reason I am not using vercel.app is because it is blocked by our school district) 
![image](https://github.com/InterstellarNetwork/Interstellar/assets/130522379/53e762d7-eca7-4df4-a53e-6447c080977d)
it may be kind of hard to tell the different but if you look at the search bar the text is different. What is hosted on the domain is coming from the same repo. could someone help?

**Comment by xbubbo** [comment]
Due to you being a skid and the same person who leaked a private password of Interstellar's you have been blocked from our Github.

**Comment by IncognitoTGT** [comment]
💀 what did bro do
