### ISSUE TITLE
[Bug] Followed instructions and the proxy returns an error

### ISSUE THREAD

**Issue by thrillhoouse** [InterstellarNetwork/Interstellar#549]
returned this:
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

**Expected behavior**
I expected the proxy to search the web as normal.

**Device Information (please complete the following information):**

- Device: Dell Chromebook 3100
- OS ChromeOs 122.0.6261.118 (Official Build) (64-bit)
- Browser Google Chrome Version 122.0.6261.118 (Official Build) (64-bit)

**Additional context**
I did switch back from ultraviolet after switching to dynamic proxy, but a simple change of settings shouldn't affect much right?

After failing, the about:blank page goes fully blank and I have to restart by running pnpm run start.

**Comment by IncognitoTGT** [comment]
Did you make the port public

**Comment by thrillhoouse** [comment]
yes

**Comment by thrillhoouse** [comment]
just made a new code space and it works, thanks for the help anyways.
