### ISSUE TITLE
[Bug] (very minor, could disregard) the frappe, macchiato, and mocha themes are the exact same.

### ISSUE THREAD

**Issue by thrillhoouse** [InterstellarNetwork/Interstellar#554]
**Describe the bug**
Three of the working themes are the exact same, color scheme and everything.

**To Reproduce**

1. Go to the settings section
2. Scroll down to themes
3. click on frappe, macchiato, and mocha themes on separate occasions and compare results (they're the same).

**Expected behavior**
Expected some change in color scheme.

**Screenshots**

**Device Information (please complete the following information):**

- Device: Chromebook
- OS  ChromeOS
- Browser Chrome

**Additional context**
I'm not trying to burden you, just something I found.

**Comment by xbubbo** [comment]
I am unable to duplicate this on the latest version of the site.

**Comment by MadjikDotPng** [comment]
I'll look into this
