### ISSUE TITLE
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]. What do I do now?

### ISSUE THREAD

**Issue by kalel4dad** [InterstellarNetwork/Interstellar#561]
I got the proxy  working using the codespaces method, but then when I typed in a place to search 
 it gives me this
RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].

- Device: Chromebook
- OS: ChromeOS
- Browser: Chrome

**Comment by kalel4dad** [comment]
Nevermind  I just fixed it.

**Comment by Thecodafr** [comment]
how?
