### ISSUE TITLE
[Bug] YouTube loads but it is a blank screen

### ISSUE THREAD

**Issue by labrizz** [InterstellarNetwork/Interstellar#580]
when opening YouTube it doesnt load anything but the search bar
open YouTube in the proxy and you will see it 
I expected to be able to be able to use youtube

I'm on a chromebook
![Screenshot 2024-04-02 9 55 24 AM](https://github.com/InterstellarNetwork/Interstellar/assets/164532004/823cf5ee-6d97-495d-a14a-18e6845cdcfa)

**Comment by xbubbo** [comment]
Youtube is currently bugged
