### ISSUE TITLE
Whatsapp not working - @oiyuninm

### ISSUE THREAD

**Issue by xbubbo** [InterstellarNetwork/Interstellar#624]
### Discussed in https://github.com/orgs/InterstellarNetwork/discussions/617

<div type='discussions-op-text'>

<sup>Originally posted by **oiyuninm** April 16, 2024</sup>
whys whatsapp not working it says Sorry, something went wrong.
We're working on getting this fixed as soon as we can.</div>

**Comment by replitidk** [comment]
nice

**Comment by replitidk** [comment]
well that kinda sucks that it cant be fixed but eh its whatever
