### ISSUE TITLE
Links! (again!)

### ISSUE THREAD

**Issue by TrickJoker312** [interstellarnetwork/Interstellar#64]
Hey, i was wondering if you have any more links for InterStellar? A lot of people found it in my school district, and it's probably gonna get blocked. I would appreciate it if you could link some below!

**Comment by Yetval1234556** [comment]
Join the Discord (https://discord.gg/gointerstellar) For a Premium Link

**Comment by imbubbo** [comment]
> Join the Discord (https://discord.gg/gointerstellar) For a Premium Link
