### ISSUE TITLE
More links, please!

### ISSUE THREAD

**Issue by TrickJoker312** [InterstellarNetwork/Interstellar#7]
I don't have Discord, and i don't have a separate computer other than my school computer, and Discord is blocked on here. Can you please tell me more links for interstellar? I'd really appreciate it!

**Comment by imbubbo** [comment]
https://potiion-of.invisibility.lol/

**Comment by imbubbo** [comment]
https://dominos.buzz/

**Comment by imbubbo** [comment]
https://fractions.interstellarmath.ink/

**Comment by TrickJoker312** [comment]
Thank you!

**Comment by imbubbo** [comment]
> Thank you!

No problem!
