### ISSUE TITLE
Herokuapp doesn't work

### ISSUE THREAD

**Issue by FatParrot25** [interstellarnetwork/Interstellar#83]
I tried to deploy to Heroku and there was no page. The logs keep saying that it is crashing.

**Comment by imbubbo** [comment]
Please ellaborate.

**Comment by FatParrot25** [comment]
I pressed the deploy to Heroku button in the readme file and deployed it with the eco dynos. Initially, it looked like it was working, but the actual page was just the Application error page, So I looked at the application page and saw these errors.
![intertellar · Logs _ Heroku and 9 more pages - Personal - Microsoft​ Edge 3_11_2023 8_56_22 PM (2)](https://user-images.githubusercontent.com/116919756/224521712-f72f7ff9-66d7-4795-9065-22a69f9f0c13.png)
I tried this a couple of times, but the same thing happened, so I was wondering if there was anything I was doing wrong on my part or if it is just an issue with the files.

**Comment by imbubbo** [comment]
> I pressed the deploy to Heroku button in the readme file and deployed it with the eco dynos. Initially, it looked like it was working, but the actual page was just the Application error page, So I looked at the application page and saw these errors. ![intertellar · Logs _ Heroku and 9 more pages - Personal - Microsoft​ Edge 3_11_2023 8_56_22 PM (2)](https://user-images.githubusercontent.com/116919756/224521712-f72f7ff9-66d7-4795-9065-22a69f9f0c13.png) I tried this a couple of times, but the same thing happened, so I was wondering if there was anything I was doing wrong on my part or if it is just an issue with the files, thank you.

Open a ticket in our discord server.

**Comment by imbubbo** [comment]
Our discord server is https://discord.gg/gointerstellar

**Comment by FatParrot25** [comment]
Thank you.
