### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by matt123491** [interstellarnetwork/interstellar#90]
When I use the discord link, this is what happens,![image](https://user-images.githubusercontent.com/40703994/226221423-b7029c5a-6b01-4b54-b26f-0460386196d8.png) 
It doesn't even show up in my server list

**Comment by Bigfoot9999** [comment]
What link are you using?

**Comment by datmonkey125** [comment]
Sorry idk if someone hacked my account or this is a misunderstanding, but I never asked any questions about discord...
________________________________

**Comment by imbubbo** [comment]
Try now @matt123491

**Comment by imbubbo** [comment]
fixed.
